### ISSUE TITLE
Powershell $env:PSModulePath delimiter

### ISSUE THREAD

**Issue by ThatRandomDude** [vexx32/PSKoans#108]
Hi, 

just i minor thing i've noticed in the readme while trying it on mac and windows:

- Windows delimiter for $env:PSModulePath is ';'
- MacOs delimiter for $env:PSModulePath is ':'

Tested with:
- Powershell 5.1, 6.1.1  on Windows
- Powershell 6.1.1 on MacOs

**Comment by vexx32** [comment]
Yep, you're absolutely right.

It should use `[System.IO.Path]::DirectorySeparatorChar` to avoid confusion and work on all platforms.

I'll update the readme soon, thank you!
