### ISSUE TITLE
AboutAssignmentAndArithmetic Arrays Example

### ISSUE THREAD

**Issue by thomasrayner** [vexx32/PSKoans#111]
[AboutAssignmentAndArithmetic L75](https://github.com/vexx32/PSKoans/blob/master/PSKoans/Koans/Foundations/AboutAssignmentAndArithmetic.Koans.ps1#L75)

```powershell
[int[]]@(1, 2, 3, 4, 5) + '17' | Should -Be @(1, 2, 3, 4, 5, 17)
```

I'm not sure this example teaches the intended lesson. By appending `'17'` to the end of the array declaration like that, PowerShell just writes the `1..5` out, and then appends `'17'` to the output. It does the same thing with strings that can't be coerced to an integer, although the comment on the line before indicates that the value is being converted.

`[int[]]@(1, 2, 3, 4, 5) + '17' | gm` returns member information for both integers and strings, indicating both types of values are written to the pipeline.

At first I thought this was occurring because no type coercion was being performed because no assignment operation was being done. Turns out, nope. Try this example.

```powershell
$a = [int[]]@(1, 2, 3, 4, 5)
$a += '17'
$a += "I love PSKoans"
$a

#outputs
1
2
3
4
5
17
I love PSKoans
```

Version info
```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.18300.1001
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18300.1001
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by thomasrayner** [comment]
Forgot to mention something I'm sure you know, but figured it would be good to track in the issue. Something like this will give the kind of output/example you're looking for, but again, it requires an assignment operation to be performed.

```powershell
[int[]]$a = @(1, 2, 3, 4, 5)
$a += '17'
$a += 'I love pskoans'

#outputs
Cannot convert value "I love pskoans" to type "System.Int32". Error: "Input string was not in a correct format."
At line:1 char:1
+ $a += 'I love pskoans'
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by vexx32** [comment]
You're almost there. The true issue is that I am casting and _then_ adding a string value. If we shuffle parentheses around it works correctly.

```PowerShell
[int[]]( @(1, 2, 3) + '17' )
```

Nice find!
