### ISSUE TITLE
Missing Planet

### ISSUE THREAD

**Issue by thomasrayner** [vexx32/PSKoans#113]
# Describe "Koan Bug, Issue, or Help Request"

[Foundations\AboutStringOperators.koans.ps1](https://github.com/vexx32/PSKoans/blob/master/PSKoans/Koans/Foundations/AboutStringOperators.Koans.ps1#L104)

## Context "The Problematic Assertions"

```powershell
It 'can limit the number of substrings' {
            $Planets = 'Mercury,Venus,Earth,Mars,Jupiter,Saturn,Uranus,Neptune'
            $Planets -split ',', 4 | Should -Be @('Mecury', 'Venus', 'Earth', 'Mars,Jupiter,Saturn,Uranus,Neptune')
        }
```
## Context "Your Attempts"

I attempted to admire a list of all the planets, including Pluto. Instead, I witnessed only 8.

## Context "Additional Information"

**Sources:** [WolframAlpha](https://www.wolframalpha.com/input/?i=is+pluto+a+planet)

**Comment by vexx32** [comment]
From the linked WolframAlpha page:

![Dwarf Planet](https://user-images.githubusercontent.com/32407840/50197864-169c8b80-0317-11e9-9858-6fbdf165510c.png)
