### ISSUE TITLE
Perhaps chapter/milemarkers for better sense of progression.

### ISSUE THREAD

**Issue by OranguTech** [vexx32/PSKoans#117]
#Background
I just started on the Koans last night, mostly enjoying it.
Currently, however, shifts from one subject to another are abrupt. "Oh, I guess I'm doing assignment operators now?"

# Describe "Functionality"

Progress is currently shown purely as a "x of (total)". I'm contemplating the idea of having the various subjects being titled and represented by "Mile Markers" in the progress display. Perhaps have them represented by a glyph/symbol, and only display the current and next subject in order to keep the output manageable/readable.

Thoughts?

**Comment by OranguTech** [comment]
That actually dovetails nicely with another aspect I was considering (but didn't mention to keep topics seperate): Maybe tracking progress more statefully between karma checks. But that got me looking into non-contiguous progress (I find myself often filling in/answering two three koans at a time, but skip one knowing I'll go back to it.) and down that rabbit-hole. 

Anyway, it would be nice to see something like "You've taken 3 more steps towards enlightenment".

But I figure I should actually progress a bit more myself.

**Comment by vexx32** [comment]
I've considered that kind of thing before, but generally haven't considered it hugely impactful. 

Here's what I've currently got with the multiple progress bars idea:

![image](https://user-images.githubusercontent.com/32407840/50381558-19211d00-0658-11e9-93dd-8f00b56be810.png)
