### ISSUE TITLE
Upgrading while learning in progress

### ISSUE THREAD

**Issue by thomasrayner** [vexx32/PSKoans#128]
# Describe "Module Bug or Issue"

If you want to upgrade from one version of PSKoans to a newer one while your learning is in progress (some koans are done, some are not done), you're going to get a bunch of errors because of changes in the engine and how some of the koans have been restructured.

## Context "The Problem"

Everybody wants the latest and greatest versions of their modules, but changing versions while your learning is in progress will result in a wide variety of different issues depending which versions you're moving between.

## Context "Expected Behavior"

An upgrade should automatically detect inprog koans and edit them accordingly, or otherwise report your progress. If a new koan is in a file that was previously completely solved, there should be a friendly message describing that scenario.

Obviously the expected behavior is up for debate, but it's not a reasonable assumption that people will start and end their PSKoans learning journey on the same version of the module - especially while hard working folks like @vexx32 @steviecoaster and @corbob are contributing new koans.

**Comment by thomasrayner** [comment]
That's totally fair. Perhaps some kind of warning or language somewhere so newbies can avoid troubleshooting a botched upgrade that they shouldn't have taken on?

**Comment by vexx32** [comment]
In what sense? Unless the user explicitly opts to `Measure-Karma -Reset` they won't be afflicted by updates unless something fundamental in the koan file format changes.

If you just mean a simple warning / confirmation that it might occasionally break something on the `Update-PSKoanUserFiles` or whatever we name it command, yeah, absolutely will do. 😄

**Comment by thomasrayner** [comment]
I'm just remembering when I went from 0.41.0 to whatever was newest then, that everything 'sploded. I'd hate for a noob to hit the same issue.

**Comment by vexx32** [comment]
I figured 😂 

Yeah, most of that was completely my fault, and I should have held the release until I was absolutely sure I'd got everything lined up properly 😄 

Shouldn't happen again (™️)
