### ISSUE TITLE
Add actual Pester tests for module functions

### ISSUE THREAD

**Issue by vexx32** [vexx32/PSKoans#13]
Minus any that aren't... really... testable -- e.g., the standard output for the `rake` function is all Write-Host and shouldn't do anything. 
Perhaps that should be Mocked to just do nothing unless params are supplied? I'm not sure. Or at least the Write-MeditationPrompt should be mocked, anyway.
Anyway, need to figure all that stuff out to make sure the core module bits and pieces work properly!

**Comment by BrandonLundt** [comment]
Regarding the tests, what does the build process look like? Is there a preference on psake vs invoke-build vs {Insert-BuildTool here} ?

**Comment by vexx32** [comment]
Haven't got that straightened out yet, I'm open for suggestions. 😄

**Comment by BrandonLundt** [comment]
I'm currently familiar with psake and have a template that we could use. It is loosely based on the psake build from Plaster. That said, I have been looking for an excuse to start using AppVeyor, so when this is ready for the PSGallery maybe we give that a go as well?

**Comment by vexx32** [comment]
I'm definitely open to both, as I have limited experience with them and this is as good a time as any to learn. :)

**Comment by vexx32** [comment]
Being worked on since #16
