### ISSUE TITLE
AboutStrings is not cross-platform

### ISSUE THREAD

**Issue by puthuppu** [vexx32/PSKoans#137]
# Describe "Koan Bug, Issue, or Help Request"
The `Evaluated Strings` context in `Foundations/AboutStrings.Koans.ps1` calls `Get-Item 'C:\Windows'` which will always fail on non-Windows machine.

## Context "The Problematic Assertions"
`Evaluated Strings` context:

```PowerShell
        It 'can do a simple expansion' {
            $Windows = Get-Item 'C:\Windows' | Select-Object -ExpandProperty FullName
            '__' | Should -Be "The windows directory is located here: $Windows"
        }
```

## Context "Your Attempts"
There are few ways this could be fixed.  If you prefer to use `Get-Item` without a variable,  you could use something like `Get-Item '.'`.  Or if you don't mind variables you could use something like `Get-Item $env:HOME`.  Or you could something less platform specific like

```PowerShell
        It 'can do a simple expansion' {
            $DayOfWeek = Get-Date | Select-Object -ExpandProperty DayOfWeek
            '__' | Should -Be "The day of the week today is $DayofWeek"
        }
```

**Comment by vexx32** [comment]
Agreed. Clearly I wrote this before I started thinking about xplat scenarios. Any of the above suggestions are perfectly serviceable, I think.
