### ISSUE TITLE
Remove Clear-Host from Measure-Karma function

### ISSUE THREAD

**Issue by stevenjudd** [vexx32/PSKoans#139]
# Describe "Functionality"

Please remove the Clear-Host command from the Measure-Karma function

## Context "Private or Public? What are the use cases? Parameters? Options?"

If someone want's a clear screen they can enter the Clear-Host command before Measure-Karma. I prefer to be able to control when my screen is cleared. This could even be a switch parameter if you want to remove the Measure-Karma text from the screen when running the command.

**Comment by vexx32** [comment]
I'm a little more inclined to make it a configurable _option_ somehow, in fact. 

I'll look into how we can make this more configurable. 🙂

**Comment by shaneis** [comment]
I did something like this trying to make a PowerShell gif. You can grab the starting position of the cursor and clear from there until a certain point.

https://github.com/shaneis/RandomScripts/blob/604784923a1773f8dda598c49aedc20fbc3a146d/Invoke-Lollercoaster.ps1#L578

Potential? 🤷‍♂️

**Comment by vexx32** [comment]
That could potentially be used, but only if the last command called was Measure-Karma and they aren't doing other things in the console as well.

We might want to look into "abbreviated" formats to display the results in as well, perhaps.
