### ISSUE TITLE
Add functionality to check progress

### ISSUE THREAD

**Issue by qlikq** [vexx32/PSKoans#150]
# Describe "Koan(s) You Suggest"

## Context "The Scope of the Koans You Suggest"

Can you please add new feature " -checkprogress " ? or "-showcompleted" , so that we can know which puzzles were completed, and which not ?

**Comment by vexx32** [comment]
Transcript from Discord on this topic for reference. 

---

@vexx32
>That shouldn't be overly difficult to implement. Do you think it makes sense to restrict it just to the file there's failing tests in? I can have it give a count of fully-completed lessons as well maybe? 

@indented-automation
>I thought the latter by default, a huge overview. Might be worth making it possible to filter on file?

@qlikq
>well for now , i have completely no idea which koans i have made/ which not, in which files .. seriously no clue
>i just look at the error that tells me where is problem ,and open the file
>and he will not tell me about it i think

@vexx32
>Yeah, the files have a defined order they'll tell you to go through them in. If you skip a puzzle it'll keep telling you that file is failing. At the moment some of them are failing within the pester module (this is fixed in next release)

**Comment by vexx32** [comment]
@qlikq This is what I have so far. Thoughts? 🙂 

![image](https://user-images.githubusercontent.com/32407840/57161607-f6e39c80-6db9-11e9-9ea6-a15d2fee3cfe.png)
