### ISSUE TITLE
I don't know if this is really a bug but Line 27 in About Arrays keeps erroring and I can't get past it

### ISSUE THREAD

**Issue by julieleach** [vexx32/PSKoans#159]
# Describe "Koan Bug, Issue, or Help Request"

**Comment by julieleach** [comment]
I put in 64 but still...

**Comment by vexx32** [comment]
Can you copy & paste that region of code from your koans file so I can see what you have? 🙂

**Comment by julieleach** [comment]
Describe 'Arrays' {

    It 'is useful for grouping related objects and values' {
        # The comma operator is used to create an array. Spaces are typically ignored.
        $Ages = 12, 25, 18, 64

        # Individual elements of an array can be accessed with square-bracket index syntax.
        # Arrays are zero-indexed; the first element is at index 0, the second at 1, etc.
        $Ages[0] | Should -Be 12
        64 | Should -Be $Ages[3]

        <#

**Comment by vexx32** [comment]
That definitely should be passing. Double check you've saved the file, and then check the `Measure-Karma` message and tell me what it's saying exactly?

**Comment by julieleach** [comment]
Yeah it's weird... because I even re-extracted the AboutArray.ps1 and started with a fresh one but still get the error.  
![SavedArray](https://user-images.githubusercontent.com/638227/56745283-12123480-6748-11e9-9764-7dd95fff6750.png)
![MeasureK](https://user-images.githubusercontent.com/638227/56745290-150d2500-6748-11e9-8e51-8ebeec5bbbed.png)

**Comment by vexx32** [comment]
This is really weird... OK, are you sure you're editing the file at `C:\Users\Name\PSKoans\Foundations\AboutArrays.Koans.ps1`? Maybe just close and open it again to be sure, that's really strange.

Also, I think you're on an older version of PSKoans; you might want to update when you finish this file and reset any files you've yet to do, so you get the updated ones for the future lessons.

Might have to do some minor changes to the older file headers for the ones you keep as they have changed a bit here and there, but nothing huge really. 😄

**Comment by julieleach** [comment]
![Is this a bad path](https://user-images.githubusercontent.com/638227/56746344-045dae80-674a-11e9-9315-ee1cdd86b139.png)

I think I saved it wrong???  I will follow your guidance in the previous comment.  Thank you :)

**Comment by vexx32** [comment]
Ah, I see. Yeah, you saved the module repo which is good, but if it's not in your usual PowerShell module paths PS won't see it as a module to import.

Use `Update-Module PSKoans` to install the latest version to your module folder. You might need to restart your PowerShell / ISE session once and then you're set.

**Comment by julieleach** [comment]
Thank you so much for your help... but now I'm getting this:
![New issue](https://user-images.githubusercontent.com/638227/56828822-23367080-6830-11e9-9de4-3aa0678857d8.png)

**Comment by vexx32** [comment]
Ah, gotcha. Yeah, you have some older koans files. You can either reset the problem files with `Measure-Karma -Reset -Topic <Name>` where <Name> is the name of the koan file minus the extensions (so for AboutArrays.Koans.ps1 it's just `AboutArrays`) or you can manually modify the headers which I'll detail below. Note that the files have probably been updated in the module since the version you had, so resetting them from the module in this way should get you the updated copy as well.

---

**To manually correct the headers:**

You're probably seeing something like this at the top of the koan file:

```powershell
using module PSKoans
[Koan(100)] # or some other number
param()
```

change it to look like this, without changing the number itself:

```powershell

```

**Comment by julieleach** [comment]
OK thanks I'll give it a try.

**Comment by vexx32** [comment]
Feel free to let me know if that doesn't sort it out for you, but I'll close this for now. 🙂
