### ISSUE TITLE
Array index producing unexpected results in AboutArrays

### ISSUE THREAD

**Issue by Eisen-Hardt** [vexx32/PSKoans#168]
# Describe "Koan Bug, Issue, or Help Request"
Array[index] returns an unexpected value, different than what is returned in a shell when declaring the same array and checking the same index.

/home/user/PSKoans/Foundations/AboutArrays.Koans.ps1
Running PSCore 6.2.0

## Context "The Problematic Assertions"
'lets you build a subset of the original array'

    It 'lets you build a subset of the original array' {
        $Array = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

        # You can also select specific index numbers
        $Index = __
        $Array[1, $Index, 4] | Should -Be @(2, 9, 5)

## Context "Your Attempts"
What I did was to set `$Index = $Array[8]`
I get the following error at runtime:

    [-] lets you build a subset of the original array
          Expected @(2, 9, 5), but got @(2, 10, 5)

If arrays are 0 indexed, then the index number + 1 should be the returned value, right? So why is `$Array[8]` returning `10`?

I try this in a regular old shell:

    PS /home/user/PSKoans/Foundations> $Array = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    PS /home/user/PSKoans/Foundations> $Array[8]
    9

And it returns 9, as expected.

**Comment by Eisen-Hardt** [comment]
It seems like I'm just missing something obvious here... I don't know how this may affect the result but I'm stepping through the lines of the file in a shell and I see what seems to me to be odd results using `[$Start..$Finish]`

    PS C:\Users\nmery> $Array = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    PS C:\Users\nmery> $Start = $Array[5]
    PS C:\Users\nmery> $Start -eq 6
    True
    PS C:\Users\nmery> $Finish = $Array[7]
    PS C:\Users\nmery> $Finish -eq 8
    True
    PS C:\Users\nmery> $Array[$Start..$Finish]
    7
    8
    9

...I guess I just don't understand this but it seems to me that `$Array[$Start..$Finish]` should return `6 7 9` and that seems related to the result I'm getting with the original issue.

Thoughts, anyone?

**Comment by Eisen-Hardt** [comment]
I stepped through the earlier part of the code and found a similar result which leads me to believe I just don't unerstand how this works.

    PS C:\Users\user> $Array = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    PS C:\Users\user> $Start = $Array[5]
    PS C:\Users\user> $Start -eq 6
    True
    PS C:\Users\user> $Finish = $Array[7]
    PS C:\Users\user> $Finish -eq 8
    True
    PS C:\Users\user> $Array[$Start..$Finish]
    7
    8
    9

It seems like I'm missing something obvious here. Why are the index results different than I think they should be?

**Comment by tomlarse** [comment]
When you set `$Index = $Array[8]`, you tell powershell to assign value `9`, since that is located at index `8` in `$Array`, so when you then tell powershell to return `$Array[1, $Index, 4]`, you tell it to return `$Array[1, 9, 4]`, which would return ´@(2, 10, 5)`.

**Comment by Eisen-Hardt** [comment]
Ah. That seems obvious now that you point it out. I guess I forgot how variables work for a second there.

Thanks for clarifying.
