### ISSUE TITLE
Issue with AboutHashtables.koans.ps1 file

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#169]
# Describe "Koan Bug, Issue, or Help Request"

AboutHashtables.koans.ps1
This might not be a serious problem, but solving it helps having an unambiguous code.
 
## Context "The Problematic Assertions"

        It 'will not implicitly convert keys and lookup values' {
            $Hashtable = @{0 = 'Zero'}

            $Hashtable[0] | Should -Be 'Zero'
            $Hashtable['0'] | Should -Be '__'
        }

## Context "Your Attempts"

        It 'will not implicitly convert keys and lookup values' {
            $Hashtable = @{0 = 'Zero'}

            $Hashtable[0] | Should -Be 'Zero'
            $Hashtable['0'] | Should -Be __
        }

## Context "Additional Information"

The single quotes around the __ must be removed, because we need to provide the $null in its place and with quotation marks around it the $null would be considered as a string. Sorry if I didn't put the codes in the right places, after all this is my first issue report on GitHub ever :)

**Comment by vexx32** [comment]
Given that the expected answer is a string, I think this is more or less in the right format. Also, bare-word parameter values will _always_ be strings. If we wanted to properly pass the null value we'd have to call this with `| Should -Be (__)`

However, this looks like one of those that I should be refactoring anyway to give a more clear error message. Having the blank on the right hand side there gives a bit of a backwards error message, and doesn't read all that well.

This file has a few issues it seems, I'll have to revisit it soon. 😄
