### ISSUE TITLE
Issue with AboutDiscovery.Koans.ps1

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#171]
# Describe "Koan Bug, Issue, or Help Request"

The total number of commands in the latest PSKoans module is 11, but there is only 4 blank space to be filled and even if there was 11 empty space, entering all the 11 name to get the point is a little unnecessary I think. So i suggest changing the code to $KoanCommands[0..3].Name to return only 4 names. 

## Context "The Problematic Assertions"

    It 'can look for commands by module' {
        $KoanCommands = Get-Command -Module 'PSKoans'

        __ | Should -Be $KoanCommands.Count
        $KoanCommands.Name | Should -Be @('__', '__', '__', '__')
    }

## Context "Your Attempts"

    It 'can look for commands by module' {
        $KoanCommands = Get-Command -Module 'PSKoans'

        11 | Should -Be $KoanCommands.Count
        $KoanCommands[0..3].Name | Should -Be @('Clear-Path', 'Get-Advice', 'Get-Enlightenment', 'Invoke-PSKoans')
    }

**Comment by vexx32** [comment]
Hmm. Are you working with the latest version of PSKoans?

This occurs because the koan is being executed inside the module itself, which exposes the internal module functions.

I thought I'd fixed this a couple versions ago -- check the version from `gmo PSKoans` please?

**Comment by arefg** [comment]
I'm working with version 0.50.1 and now I got an even bigger problem when I run this 
"$CommandCount = Get-Command | Measure-Object | Select-Object -ExpandProperty Count"
in VSCode  I get 2240 and after putting this number in
2240 | Should -Be $CommandCount
and saving the file and running Measure-Karma I get an error for this line and the expected command count is 2227.
So the only solution I can think of is to put the number returned by the Measure-Karma in the code even if running the above 2 lines by hitting F8 in VSCode will return an error with this number.
I think this is happening because the command count is different based on the PowerShell host running the Get-Command cmdlet and also if someone installs a new module or remove an existing one, the next time he wants to continue using PSKoans he will get an error in this line and need to put the new value each time to pass this test.

**Comment by tomlarse** [comment]
I ran in to this as well, the module almost always get a different count on commands than if you run `Get-Command | Measure-Object | Select-Object -ExpandProperty Count` manually.

I thought it might be because i'd have accidentally loaded a module between filling out the answer and measuring, but even if I run it manually and then enter the result I get, the number is different when run by PSKoans during `Measure-Karma`.

I don't think PSKoans sees a different set of commands, if I run `gcm` on the module, this is the result. 

```
C:\Users\Tom-IngeLarsen\PSKoans> gcm -Module PSKoans

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Clear-Path                                         0.50.1     PSKoans
Alias           Get-Advice                                         0.50.1     PSKoans
Alias           Get-Enlightenment                                  0.50.1     PSKoans
Alias           Invoke-PSKoans                                     0.50.1     PSKoans
Alias           Test-Koans                                         0.50.1     PSKoans
Function        Get-Blank                                          0.50.1     PSKoans
Function        Get-PSKoanLocation                                 0.50.1     PSKoans
Function        Measure-Karma                                      0.50.1     PSKoans
Function        Register-Advice                                    0.50.1     PSKoans
Function        Set-PSKoanLocation                                 0.50.1     PSKoans
Function        Show-Advice                                        0.50.1     PSKoans
```

**Comment by vexx32** [comment]
Oh, that makes sense. OK, yeah, I just haven't updated this koan in several versions, and the module itself has expanded. _And_ I totally forgot that it would also pull aliases.
