### ISSUE TITLE
Scoping bug in AboutPSProviders.Koans.ps1

### ISSUE THREAD

**Issue by tomlarse** [vexx32/PSKoans#172]
# Describe "Koan Bug, Issue, or Help Request"

https://github.com/vexx32/PSKoans/blob/e0a54b0363c84ef67262a34dad48caa9fd745e02/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L36

## Context "The Problematic Assertions"

Context 'Direct Access'

The `$Aliases` variable is given a value here https://github.com/vexx32/PSKoans/blob/e0a54b0363c84ef67262a34dad48caa9fd745e02/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L36

Under `It 'can be queried with generic provider cmdlets'`, but then under `It 'can create aliases too!'` we try referencing it again, but `$Aliases` doesn't exist in that scope. 

## Context "Your Attempts"

Moved `$Aliases = Get-ChildItem 'Alias:'` to line 34 so that it gets created in the entire Context scope.

**Comment by vexx32** [comment]
Hmm, is that so? I was actually under the impression than an `It` block was not itself a separate scope. From memory, they should be scoped to the closest parent `Describe` / `Context` block.

/cc @nohwnd have I made a terrible assumption here?

Or does this work, and then I fail to clarify that's how it works / should I change this anyway as it makes for inconsistent presentation to pupils?

**Comment by nohwnd** [comment]
`It` makes its own scope, so that variables from one `It` do not leak to other `It` blocks. So @tomlarse is correct. 

```powershell
Describe "d" { 
    $a = 10 
    Write-Host $a
    It "i" {
        $a = 1
        Write-Host $a
    }
    Write-Host $a 
}

## output 
# 10 
# 1 
# 10
```

**Comment by tomlarse** [comment]
Also, here you've done it the same way

https://github.com/vexx32/PSKoans/blob/e0a54b0363c84ef67262a34dad48caa9fd745e02/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L177

**Comment by vexx32** [comment]
Whoops. Cheers @nohwnd, not sure where I picked up that assumption from... 😂

**Comment by nohwnd** [comment]
Maybe you confused it with Mock or how if/foreach/other stuff works :)

**Comment by vexx32** [comment]
_Very_ possible. Very possible. 😄 

Thanks!
