### ISSUE TITLE
Issues with 'Filesystem Provider'

### ISSUE THREAD

**Issue by tomlarse** [vexx32/PSKoans#174]
# Describe "Koan Bug, Issue, or Help Request"

https://github.com/vexx32/PSKoans/blob/e0a54b0363c84ef67262a34dad48caa9fd745e02/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L130

### Context 'Filesystem Provider'

I was a bit confused about this whole context. To begin with, I think that it needs more explanations, especially clarifying that `TestDrive:` is a drive created by PSKoans. 

---
https://github.com/vexx32/PSKoans/blob/e0a54b0363c84ef67262a34dad48caa9fd745e02/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L149
Since we insert random newlines in the tempfile, its `Length` is random on every `Measure-Karma`, so answer would be `$File.Length | Should -Be $File.Length`

If the file is created like this, it would be `10000` every time, and we would have newlines in the file.
```
-join (1..10000 | ForEach-Object {
    Get-Random -Minimum 32 -Maximum 96 |
    ForEach-Object {
        if ($_ -match '[25]0$'){
            "`n"
        } else {
            [char]$_ -as [string]
        }
    }
}) | Set-Content -Path $Path
```
---
https://github.com/vexx32/PSKoans/blob/e0a54b0363c84ef67262a34dad48caa9fd745e02/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L154
This would also be random every time? Is the answer `$FirstLine | Should -Be $FirstLine`?

**Comment by vexx32** [comment]
Hehe, yeah, it sounds like I definitely revisit this one.

`TestDrive:` is created by Pester technically, but yeah I should definitely point that out. 😄

**Comment by tomlarse** [comment]
Well, I learned something about Pester today too then! :D That seems super useful!

**Comment by arefg** [comment]
Because TestDrive: is created on the fly when running Measure-Karma, you cannot test the code by running it line by line and its hard to figure out what's really going out behind the scene. So I think using a local address like C: would be nicer. ;)

**Comment by vexx32** [comment]
Not possible. PSKoans can run on Linux too, so it needs a dynamically-created directory. 

It _could_ use `$env:TEMP` I suppose?
