### ISSUE TITLE
Variable scoping issue in AboutTeeObject

### ISSUE THREAD

**Issue by tomlarse** [vexx32/PSKoans#176]
# Describe "Koan Bug, Issue, or Help Request"

AboutTeeObject

## Context "The Problematic Assertions"

`It 'passes the object on through the pipeline'` and
`It 'can store the object(s) into a variable'`

results in

`Expected $null, but got @(1, 2, 3, 4, 5, 6, 7, 8, 9, 10).`
`Expected $null, but got @('alpha', 'beta', 'gamma')`

## Context "Your Attempts"
Seems to be a scoping issue in Pester

This fails
```
describe 'test1' {
    it 'num' {
        1..3 | tee-object -variable num | should -be $num
    }
}
```

But this works
```
describe 'test2' {
    $num = 1...3
    It 'num' {
        1..3 | Tee-Object -variable num | should -be $num
    }
}
```

**Comment by tomlarse** [comment]
nvm, must be something else. This does not work either

```
describe 'test2' { 
     $num = ''
     It 'num' {
        1..3 | Tee-Object -variable num | should -be $num 
      }
}
```

**Comment by vexx32** [comment]
Huh, that's... weird... oh, I wonder if Tee-Object doesn't set the variable until the pipeline is _finished_.

That would make some sense.

**Comment by tomlarse** [comment]
Yeah, that has got to be it. 

![image](https://user-images.githubusercontent.com/4574656/58174015-2856d600-7c9d-11e9-98c6-1fa2becbebf5.png)

**Comment by arefg** [comment]
I think breaking it into 2 lines is the simplest solution.
        1..10 | Tee-Object -Variable n 
        1..10 | Should -Be $n
