### ISSUE TITLE
Get-Random in AboutWhereObject

### ISSUE THREAD

**Issue by tomlarse** [vexx32/PSKoans#177]
# Describe "Koan Bug, Issue, or Help Request"

AboutWhereObject

## Context "The Problematic Assertions"

`It 'can filter on object propertes'`

```
$Result = $ItemsWithNumbers |
            Get-Random |
            Select-Object -ExpandProperty Name
```
Wouldn't this have a different result on every `Measure-Karma`?

**Comment by vexx32** [comment]
Yeah, that's no good. 😂
