### ISSUE TITLE
Attempted to divide by zero on Show-MeditationPrompt.ps1

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#178]
When I use "Measure-Karma -Topic" and the name of any completed topic after it, I get an "Attempted to divide by zero."  message in the output. Although this is not a serious bug but I thought it worth mentioning.

This is the complete error message:

Attempted to divide by zero.
At C:\Program Files\WindowsPowerShell\Modules\PSKoans\0.50.1\Private\Show-MeditationPrompt.ps1:172 char:17
+ ...             $PortionDone = ($KoansPassed / $TotalKoans) * $ProgressWi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

My PowerShell and module versions are:

Name           Version
----                -------
PSKoans        0.50.1

Name                           Value
----                           -----
PSVersion                      5.1.17763.503
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.503
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by vexx32** [comment]
Where are you executing this? In the ISE? VS Code? Regular PS window?

Thought I had this one sorted, heh. :)

**Comment by arefg** [comment]
In VS Code

**Comment by vexx32** [comment]
Very strange, I definitely have that working in my VS Code. Can you check the following values in your VS Code prompt for me?

```powershell
$host.UI.RawUI.WindowSize
$host.UI.RawUI.BufferSize
```

And if it's none of those... oh, check `Get-PSKoanLocation` and make sure that it's a directory that exists; you might need to create it and run `Measure-Karma -Reset` once to get everything that should be there put where it belongs.

Usually it handles this sort of thing well enough, though.

**Comment by arefg** [comment]
These are my valuse for WindowsSize and BufferSize:
PS C:\Users\Aref\PSKoans> $host.UI.RawUI.WindowSize

Width Height
----- ------
   80     21


PS C:\Users\Aref\PSKoans> $host.UI.RawUI.BufferSize

Width Height
----- ------
   80   3000

The PSKoans folder exist:
PS C:\Users\Aref\PSKoans> Get-PSKoanLocation
C:\Users\Aref\PSKoans

I also cut my PSKoans folder and paste it somewhere else and ran the Measure-Karma -Reset and then completed the AboutAssertion topic but again I get the same error when running Measure-Karma -Topic AboutAssertions.

**Comment by vexx32** [comment]
Can you check `Get-Module Pester` and see what version of Pester you have installed? It _shouldn't_ matter, but clearly something is different to how I have it locally here and in CI.

**Comment by arefg** [comment]
Its 4.7.3

PS C:\Users\Aref\PSKoans> Get-Module Pester

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.7.3      Pester                              {Add-AssertionOper...

**Comment by tomlarse** [comment]
I also have this with Pester 4.8.1

**Comment by vexx32** [comment]
Strange. I updated to Pester 4.8.1 as well, and I have yet to see this... 🤔

**Comment by alliedcvil** [comment]
Have the same behavior and then it refers me to https://leanpub.com/powershell-by-mistake

**Comment by vexx32** [comment]
Can you please run `Measure-Karma -Verbose` and see what it registers for the total number of koans and the karma value?

**Comment by tomlarse** [comment]
![image](https://user-images.githubusercontent.com/4574656/58433738-d1943680-80b8-11e9-83bf-934c6774d044.png)
It seems to find them all correctly. Behaves the same way in PS 5.1 and 6.2, as well as elevated. Can it be tied to locale or something?

In the code, the verbose message for Total Koans comes from https://github.com/vexx32/PSKoans/blob/f67a246c2b525936698076159f93d4b44144380a/PSKoans/Public/Measure-Karma.ps1#L108 while the number that it divides by is https://github.com/vexx32/PSKoans/blob/f67a246c2b525936698076159f93d4b44144380a/PSKoans/Public/Measure-Karma.ps1#L174

If there are errors however, it divides by https://github.com/vexx32/PSKoans/blob/f67a246c2b525936698076159f93d4b44144380a/PSKoans/Public/Measure-Karma.ps1#L162

Maybe `$PesterTests.TotalCount` evaluates to zero on some systems?

**Comment by vexx32** [comment]
Aye, that is my thought, though I'm not sure why it would be different. 
Also... that's very odd. Why is yours loading two versions of the module?

**Comment by tomlarse** [comment]
wow, didn't notice that.

![image](https://user-images.githubusercontent.com/4574656/58435103-3eaaca80-80bf-11e9-906a-b9e13be9f2f1.png)

hmm.

**Comment by tomlarse** [comment]
Not the same in ps 6.2 though

![image](https://user-images.githubusercontent.com/4574656/58435215-ad882380-80bf-11e9-975f-c113d5650601.png)

Let me run the same there.

**Comment by tomlarse** [comment]
It's a lot less verbose there
![image](https://user-images.githubusercontent.com/4574656/58435255-eb854780-80bf-11e9-8421-cc2777871de1.png)

**Comment by vexx32** [comment]
Is this only when using `-Topic` or does it occur in all cases?

**Comment by tomlarse** [comment]
It only appears on `-Topic` if I run it on a topic that is complete. I haven't completed all Koans, so I don't know how it would behave then. What would be the easiest way to test that?

**Comment by tomlarse** [comment]
It works fine on one that is not complete:
![image](https://user-images.githubusercontent.com/4574656/58435867-fdb4b500-80c2-11e9-8a01-0cbb702f3622.png)

**Comment by tomlarse** [comment]
But `Measure-Karma` uses `TotalKoans   = $TotalKoans` when `$PesterTests.FailedCount -gt 0`, but `TotalKoans  = $PesterTests.TotalCount` else.

**Comment by vexx32** [comment]
Gotcha, so we have a logic issue. Should be a relatively quick fix. I'll get to it when I can, or one of you fellows is welcome to PR the fix if you'd like. ^^

**Comment by alliedcvil** [comment]
It works now for me after several attempts at updating Pester.
