### ISSUE TITLE
Issue with AboutPSProviders

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#179]
On the following lines there should be '__' instead of __. 

37        __ | Should -Be $Aliases.Name[0]

38        __ | Should -Be $Aliases.Definition[0]

72        $CmdletName = __

95        __ | Should -Be $Alias:gci

102      __ | Should -Be $AliasTarget

241      __ | Should -Be $VariableData.Options

257      __ | Should -Be $Variables.Where{$_.Name -eq 'ConfirmPreference'}.Value

279      __ | Should -Be $Info.Options

288      __ | Should -Be $Get

I think you tried to show that the number of aliases will grow by one after creating a new alias, so assuming that we need to reassign $Aliases = Get-ChildItem 'Alias:' before line 55 to be able to see the new result, otherwise, this line will be the exact copy of line 49.

48    It 'can create aliases too!' {
49               __ | Should -Be $Aliases.Count
50
51               New-Item -Path 'Alias:\grok' -Value 'Get-Item' -ErrorAction SilentlyContinue
52               $File = grok '__' -ErrorAction SilentlyContinue
53
54               $File | Should -BeOfType 'System.IO.FileInfo'
55               __ | Should -Be $Aliases.Count
56
57               Remove-Item -Path 'Alias:\grok'
58           }

On this block, I had to change the index number so that I can pass the test because my $Functions[5] is 'AfterAll' function of the Pester module which has no verb or noun. This actually does not always result in the same names so it's hard to find an index that can be applied to everyone and every situation.

    It 'allows access to all currently loaded functions' {
        # Most proper functions are named in the Verb-Noun convention
        '__' | Should -Be $Functions[5].Verb
        '__' | Should -Be $Functions[5].Noun
        '__' | Should -Be $Functions[5].Name

        '__' | Should -Be $Functions[4].Name
    }

On these lines, I couldn't get them to work no matter what I put as the answer.  It keeps telling "no exception was thrown.". I'm not sure if I'm missing something or there is something wrong with these lines.

251      {Get-Item 'Variable:\Test'} | Should -Throw -ExceptionType __

268      {Remove-Item 'Variable:\Test'} | Should -Throw -ExceptionType __

And finally, on line 267  __ | Should -Be $Var I couldn't find any other answer but $Var. This one is for my own information so it's not an issue. :)

**Comment by vexx32** [comment]
Nice finds, thank you! I'll have to go over this file at some point soon. :)

**Comment by A298B112** [comment]
I am also having issue in the next block:

 It 'can be accessed with Get-Alias' {
            $AliasObjects = Get-ChildItem 'Alias:'
            $AliasObjects2 = Get-Alias

            173 | Should -Be $AliasObjects2.Count
            $AliasObjects | Should -Be $AliasObjects2
        }

this is what I get on my host:
PS C:\> $AliasObjects2 = Get-Alias
PS C:\> $AliasObjects2.Count
173

however, error message says "Expected 166, but got 173."

So I don't understand where the 166 come from?
