### ISSUE TITLE
Issue with AboutSelectObject

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#180]
$UniqueItems is @(6, 1, 4, 8, 7, 5, 3, 9, 2) which has a length of 9 but this line has 10 members and the order is also important which means we had to replace even the hardcoded values with the correct values of  (6, 1, 4, 8, 7, 5, 3, 9, 2) and delete the last blank space.  Also there is a 10 in it ;)
5, '__', 10, 9, '__', '__', '__', 7, '__', '__' | Should -Be $UniqueItems

**Comment by vexx32** [comment]
Good catch, thank you!
