### ISSUE TITLE
Issue with AboutMeasureObject

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#181]
In the following block, I get this error when there is a -Count parameter in it, but by omitting the -Count it works fine:

A parameter cannot be found that matches parameter name 'count'

It 'can count objects' {
        $Numbers |
            Measure-Object -Count |
            Select-Object -ExpandProperty Count |
            Should -Be __

        $Files |
            Measure-Object -Count |
            Select-Object -ExpandProperty Count |
            Should -Be __
    }

There is also a problem with the average value in this block, I get this error despite entering the correct value, and the numbers in error are exactly the same.

Expected 20.8706199460916, but got 20.8706199460916

    It 'can operate on object properties' {
        $Data = $Files.BaseName | Measure-Object -Property Length -Sum -Average
        __ | Should -Be $Data.Sum
        __ | Should -Be $Data.Average
    }

**Comment by A298B112** [comment]
Measure-Object doesn't have -Count parameter. Please check this link: https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Measure-Object?view=powershell-6 

Overall, I am having also issues with AboutMeasureObject Koan. 

Further down on the file you will see this block:

  It 'can sum numerical objects' {
        $StopIndex = __

        $Numbers[0..$StopIndex] |
            Measure-Object -Sum |
            Select-Object -ExpandProperty Sum |
            Should -Be 6046
    }

two issues with this block:
1. there is no such a number K that 1+...+K results 6046. If $StopIndex = 109 the results will be 5995, if $StopIndex = 110 then the result will be 6105
2. $Numbers[0..$StopIndex] should be $Number = 1..$StopIndex. Writing $Numbers[0..$StopIndex] makes sense if $Numbers was an array.

**Comment by vexx32** [comment]
`$Numbers` is an array; it gets defined a bit further up. 🙂 

https://github.com/vexx32/PSKoans/blob/2fbcaf44282adda0310b927278151786a13a0c96/PSKoans/Koans/Cmdlets%201/AboutMeasureObject.Koans.ps1#L11-L18

It's possible I miscalculated the sum there, but I don't think so?

**Comment by A298B112** [comment]
@vexx32 you are right, I went through it one more time. Now it is clear. :-)

**Comment by vexx32** [comment]
Awesome! I added a closing reference to your PR, so this issue can close when that is completed. 😊
