### ISSUE TITLE
Issues with AboutModules

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#184]
There is an 's' missing in Modules[2].Version in line 36
36          $VersionOfThirdModule | Should -Be $Module[2].Version

The result of Get-Module seems to be different when running manually in VSCode and when its run by Measure-Karma. I get this error on line 35 and similar error for lines 36,37:

35         $FirstThreeModules | Should -Be $Modules[0..2].Name

            Expected @('CimCmdlets', 'DummyTypes', 'Microsoft.PowerShell.Utility'), but got @('CimCmdlets', 'DummyTypes', 'Microsoft.PowerShell.Management').

Find-Module has a similar problem in line 85, I get a similar error for line 93.

I think the scope of the following line(115) must move up to the Describe block because in line 121 and 125 I get an error saying "Expected $null".

               $Module = New-Module -Name 'PSKoans_TestModule' -ScriptBlock {}

               Expected 4.7.3, but got '4.8.1'.

The module's GUID in line 125 is different on every Measure-Karma, so I had to comment the whole line to pass the test.

In line 167 there is an extra space in "-BeNullOrEmpty"

167              Import-Module 'TestDrive:\TestModule.psm1' | Should -Be NullOrEmpty

Before line 177 we need to reassign $ImportedModule = Get-Module -Name 'TestModule' or move it up one scop.

                  
177            @('Test-ModuleFunction') | Should -Be $ImportedModule.ExportedCommands.Keys

One more thing there should be a '__' instead of __ in line 121

121              __ | Should -Be $Module.ModuleBase

Lots of things to cover up in this one I think :wink: :smile:

**Comment by vexx32** [comment]
Well spotted, and thank you! 😄
