### ISSUE TITLE
Issues with AboutStringBuilder

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#188]
In 'can append new lines' block starting at line 61, filling the blank spaces with just "Hello!" and "Goodbye!" generates an error: 

             Expected: 'Hello!\r\nGoodbye!\r\n'
             But was:  'Hello!\nGoodbye!'

I think we need to either use one of the followings to return the expected string for $StringBuilder.ToString() 

                 1            $ExpectedString = "Hello!`r`nGoodbye!`r`n"

                 or

                 2            $ExpectedString = @"
                 Hello!`r
                 Goodbye!`r`n
                 "@

In line 78, $FormatItems is missing as AppendFormat argument:
                  
                     $StringBuilder.AppendFormat("{0} is {1}.", $FormatItems)

In Line 151, since there are 3 property names instead of 

              $PropertyName = __

I think it's better to have something like this:

             $PropertyName = "__", "__", "__"

In line 157 and 161, the variable names are not matching. one of them should change to the other one.
                
                **$ExpectedCount** = $Properties |
                Measure-Object |
                Select-Object -ExpandProperty Count

               $PropertyCount | Should -Be **$ExpectedPropertyCount**

in the block starting at line 165, I'm not sure what is the purpose of it, maybe you missed something you were trying to convey because the only solution is to put the same number for $FinalStringLength to pass the test.

             It 'indicates the current length of the string' {
            $FinalStringLength = __

            $StringBuilder.ToString().Length | Should -Be $StringBuilder.Length
            $FinalStringLength | Should -Be $StringBuilder.Length
        }

**Comment by BrandonLundt** [comment]
> In 'can append new lines' block starting at line 61, filling the blank spaces with just "Hello!" and "Goodbye!" generates an error:

Would it be more effective to have the here-string populated and ask the user to fill in the `$StringBuilder.AppendLine`
e.g. 
```powershell
It 'can append new lines' {
            $StringBuilder = [System.Text.StringBuilder]::new()
            $StringBuilder.AppendLine('__')
            $StringBuilder.AppendLine('__')

            $ExpectedString = @"
Hello!
GoodBye!

"@
```

**Comment by vexx32** [comment]
I don't think that's the real issue there, unfortunately. The problem will be that the koan files only use `\n` for line endings, as that's what Git supports most of the time and works on most OSes, but `StringBuilder.AppendLine()` probably checks `[Environment]::NewLine` for the line ending to use... 🤔 

I guess if we populated the here string and added the carriage return into it deliberately it would work on Windows, but it would then fall apart on Linux.

**Comment by BrandonLundt** [comment]
I don't have a linux system to directly test on, but it seems to me it is really only a matter of appendline is appending a new line character at the end; regardless if it is a \r\n or \n. Which will inherently require this here-string to have additional line ending.

https://github.com/vexx32/PSKoans/blob/3320e2c4370a4fd248753b6622a0bd234f8677dc/PSKoans/Koans/Constructs%20and%20Patterns/AboutStringBuilder.Koans.ps1#L66-L69

As an example this passes in windows:
```PowerShell
It 'can append new lines' {
    $StringBuilder = [System.Text.StringBuilder]::new()
            $StringBuilder.AppendLine('Hello!')
            $StringBuilder.AppendLine('GoodBye!')

            $ExpectedString = @"
Hello!
GoodBye!

"@
$StringBuilder.ToString() | Should -Be $ExpectedString
    }
}

Describing System.Text.StringBuilder
  [+] can append new lines 37ms
```

This fails in windows:
```PowerShell
It 'can append new lines' {
    $StringBuilder = [System.Text.StringBuilder]::new()
            $StringBuilder.AppendLine('Hello!')
            $StringBuilder.AppendLine('GoodBye!')

            $ExpectedString = @"
Hello!
GoodBye!
"@
$StringBuilder.ToString() | Should -Be $ExpectedString
    }
}

Describing System.Text.StringBuilder
  [-] can append new lines 29ms
    Expected strings to be the same, but they were different.
    Expected length: 16
    Actual length:   18
    Strings differ at index 16.
    Expected: 'Hello!\r
    GoodBye!'
    But was:  'Hello!\r
    GoodBye!\r
    '
    -----------------------------^
    13: $StringBuilder.ToString() | Should -Be $ExpectedString
```

In any event, I advocate for leaving the blank lines in AppendLine() as the focus of this specific Koan is on StringBuilder. The here-string is strictly a means validate against.

**Comment by BrandonLundt** [comment]
I would also be on board with saying that specific part of this Issue isn't actually an problem to fix and leave it as is. I will submit a pull request for what I have and can easily modify it accordingly.
