### ISSUE TITLE
Issues  with AboutCustomObjects

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#190]
Line 36: Instead of __ it should be ' __ '

                      __ | Should -Be $Object.Parent.Name

Line 40: I think 'Enter Property Name' should be replaced by something like  'PropertyValue' since it's the value field of the property and not its name and also in this case, we are not going to change it anyway. This will help to better understand the structure and there will be no misunderstanding.

:x: $Object = [PSCustomObject]@{ '__' = 'Enter Property Name' }

:heavy_check_mark:  $Object = [PSCustomObject]@{ '__' = 'PropertyValue' }

**Comment by vexx32** [comment]
Yeah, I agree, that makes a lot more sense 👍
