### ISSUE TITLE
AboutRedirection

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#195]
Line 102 and 103: $FileContent index should be 4 and 5 respectively and there should be 4 spaces at the beginning of these messages to be exactly like the error message and to be able to pass the test:

             "    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException" | Should -Be $FileContent[4]
             "    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException" | Should -Be $FileContent[5]

**Comment by vexx32** [comment]
@arefg when you call `Write-Error` how does it show for you? For me, at least, it doesn't have spaces in front of the CategoryInfo/ErrorID lines:

![image](https://user-images.githubusercontent.com/32407840/60391268-560f1600-9ab8-11e9-95eb-b4dbf742cd85.png)
