### ISSUE TITLE
AboutErrorHandling

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#196]
Line 43: $ErrorRecord.TargetObject in not null so there should be a "-Not" in this test:

:x: $ErrorRecord.TargetObject | Should -BeNullOrEmpty
:heavy_check_mark: $ErrorRecord.TargetObject | Should -Not -BeNullOrEmpty

Line 55: There should be " __ " instead of ' __ ' because there is a single quotation in the text(TestDrive:\This_Shouldn't_Exist).

:x: ' __ ' | Should -Be $Error[0].TargetObject
:heavy_check_mark:" __ " | Should -Be $Error[0].TargetObject

Line 74: Since $ErrorRecord.InvocationInfo.PositionMessage is more than one line, there should be a way of selecting just the second line, I know this is not the best way but the test will pass :wink: I'm sure you can come up with a better substitute for this line:

        '+             throw "A challenge to the sky!"'+"`r" | Should -Be $ErrorRecord.InvocationInfo.PositionMessage.Split("`n")[1]

Line 138: The function name has not been defined before, so I guess you were going to use "Write-SimpleError" instead of "Test-SimpleWriteError"

:x:$ErrorRecord = Test-SimpleWriteError 2>&1
:heavy_check_mark:$ErrorRecord = Write-SimpleError 2>&1

Line 147: There should be a comma instead of a period in the middle of ' __ . __ '

:x:' __ . __ ' | Should -Be $ErrorRecord.FullyQualifiedErrorId
:heavy_check_mark:' __ , __ ' | Should -Be $ErrorRecord.FullyQualifiedErrorId

Line 235: Should in the text is spelled wrong

Line 258: 

:x:                [CmldetBinding()]
:heavy_check_mark:                [CmdletBinding()]

Line 72: $ErrorRecord.InvocationInfo.ScriptLineNumber is 2 when running manually but after running Measure-Karma it returns an error saying  "Expected 23, but got 2" :thinking:

**Comment by BrandonLundt** [comment]
> Line 43: $ErrorRecord.TargetObject in not null so there should be a "-Not" in this test:
>
>❌ $ErrorRecord.TargetObject | Should -BeNullOrEmpty
>✔️ $ErrorRecord.TargetObject | Should -Not -BeNullOrEmpty

I disagree, it feels more like the whole IT should be reviewed/rewritten/moved; at a minimum this line should be removed. Point in case: https://github.com/vexx32/PSKoans/blob/1edc1b91e6f92eae19dec46bb019c9222477218d/PSKoans/Koans/Constructs%20and%20Patterns/AboutErrorHandling.Koans.ps1#L41-L56

This is the only time that $error is referenced. Otherwise all other tests use $ErrorRecord.

**Comment by BrandonLundt** [comment]
> Line 72: $ErrorRecord.InvocationInfo.ScriptLineNumber is 2 when running manually but after running Measure-Karma it returns an error saying "Expected 23, but got 2"

Depending on what you meant by "running manually" this could make sense. Measure-Karma will have this error thrown at line 23. Whereas if I at a command prompt run:
```
$ErrorRecord = try {
      throw "A challenge to the sky!"
  }
 catch {
    $_
}
```

The the line would be 2.
