### ISSUE TITLE
Issue with AboutArrays - Misleading Text

### ISSUE THREAD

**Issue by figueroadavid** [vexx32/PSKoans#206]
# Describe "Koan Bug, Issue, or Help Request"
In the section at line 84 the comment of '# Is anything missing?' is misleading. It leads the reader to think that something is actually missing from the array definition.  A much more direct statement would indicate that the user should fix the array definition.  

AboutArrays.Koans.ps1

## Context "The Problematic Assertions"

         Negative numbers can also form a range and extract subsets
        $Array[-4..-1] | Should -Be @(5, 6, 7) # The array definition needs to be corrected.

## Context "Your Attempts"

N/A

**Comment by EVWorth** [comment]
This is now on Line 90
