### ISSUE TITLE
Possibly rename the Koans files to make them list in the correct order

### ISSUE THREAD

**Issue by figueroadavid** [vexx32/PSKoans#207]
# Describe "Koan(s) You Suggest"

This is about the general structure of the file names for the Koans. The Koans files themselves list in alphabetical order, but the actual koans sections contain their own position number causing them to be accessed in a different order.  

My suggestion is to rename the files so that the appear in the order they are actually accessed.  
For example, in the Foundations section, here are the Koans files:
```
AboutArrays.Koans.ps1
AboutAssertions.Koans.ps1
AboutAssignmentAndArithmetic.Koans.ps1
AboutComparison.Koans.ps1
AboutConditionals.Koans.ps1
AboutFunctionsAndScriptBlocks.Koans.ps1
AboutHashtables.Koans.ps1
AboutLoopsAndPipelines.Koans.ps1
AboutOrderOfOperations.Koans.ps1
AboutStringOperators.Koans.ps1
AboutStrings.Koans.ps1
AboutTheStockChallenge.Koans.ps1
AboutTypeOperators.Koans.ps1
AboutVariables.Koans.ps1
```
However, based on the position variables, they are accessed in this order:
```
AboutAssertions.Koans.ps1:[Koan(Position = 101)]
AboutVariables.Koans.ps1:[Koan(Position = 102)]
AboutFunctionsAndScriptBlocks.Koans.ps1:[Koan(Position = 103)]
AboutOrderOfOperations.Koans.ps1:[Koan(Position = 104)]
AboutArrays.Koans.ps1:[Koan(Position = 105)]
AboutAssignmentAndArithmetic.Koans.ps1:[Koan(Position = 106)]
AboutComparison.Koans.ps1:[Koan(Position = 107)]
AboutStrings.Koans.ps1:[Koan(Position = 108)]
AboutStringOperators.Koans.ps1:[Koan(Position = 109)]
AboutConditionals.Koans.ps1:[Koan(Position = 110)]
AboutTypeOperators.Koans.ps1:[Koan(Position = 111)]
AboutHashtables.Koans.ps1:[Koan(Position = 112)]
AboutLoopsAndPipelines.Koans.ps1:[Koan(Position = 113)]
AboutTheStockChallenge.Koans.ps1:[Koan(Position = 114)]
```
Depending on how they are accessed inside the Koans module, I would rename them so that they stay in the correct order.. for example:
```
101_AboutAssertions.Koans.ps1:[Koan(Position = 101)]
102_AboutVariables.Koans.ps1:[Koan(Position = 102)]
103_AboutFunctionsAndScriptBlocks.Koans.ps1:[Koan(Position = 103)]
104_AboutOrderOfOperations.Koans.ps1:[Koan(Position = 104)]
105_AboutArrays.Koans.ps1:[Koan(Position = 105)]
106_AboutAssignmentAndArithmetic.Koans.ps1:[Koan(Position = 106)]
107_AboutComparison.Koans.ps1:[Koan(Position = 107)]
108_AboutStrings.Koans.ps1:[Koan(Position = 108)]
109_AboutStringOperators.Koans.ps1:[Koan(Position = 109)]
110_AboutConditionals.Koans.ps1:[Koan(Position = 110)]
111_AboutTypeOperators.Koans.ps1:[Koan(Position = 111)]
112_AboutHashtables.Koans.ps1:[Koan(Position = 112)]
113_AboutLoopsAndPipelines.Koans.ps1:[Koan(Position = 113)]
114_AboutTheStockChallenge.Koans.ps1:[Koan(Position = 114)]
```

This will make it much easier to locate the file and edit them.

**Comment by vexx32** [comment]
Mmh. Maybe? It was actually like this originally, but to be honest I found that at least for myself, keeping track of all the numbers was harder and more annoying than scanning down an alphabetical list. 

Also, while this might make it easier to go through the normal order, it also makes it a bit trickier for anyone who wants to do things in their own order, because you can't rely on the alphabetical order to help you find anything.

**Comment by figueroadavid** [comment]
I'd think matching the position to the file name would make it easier than the "wall of text".. for example.. the numerical value just stands out more.  And if you are keeping the position parameter in the file, then even when they go in their own order, it's very easy to find it at the top. :-)
