### ISSUE TITLE
Issue with AboutVariables

### ISSUE THREAD

**Issue by strakh-alex** [vexx32/PSKoans#210]
Please, help me with the next issue:

I got a strange error on my work PC in AboutVariables module, but on my Home PC everything works fine:

"Expected the value to have type [bool] or any of its subtypes, but got 'True' with type [string]."

Code snippet:
        $String = [string]$true

        $Number | Should -BeOfType [int]
        $String | Should -BeOfType [string]

Both PCs have the latest Windows 10 installed (Pro and Enterprise) with PowerShell 5.1.

**Comment by strakh-alex** [comment]
Sorted out

**Comment by EVWorth** [comment]
What was your problem?

**Comment by strakh-alex** [comment]
> 
> 
> What was your problem?

Measure-Karma tried to use C:\Users\<USER>\ folder instead of the folder specified in $env.
Fixed by moving PSKoand to the user folder.

**Comment by vexx32** [comment]
Ah, gotcha. If you've recently updated you'll need to use `Set-PSKoanLocation` to update the location if you want to use a non-default value. Pop it in you PowerShell profile script to keep a semipermanent setting until I get a proper config storage setup. :)
