### ISSUE TITLE
Issue with AboutComparison.Koans.ps1

### ISSUE THREAD

**Issue by EVWorth** [vexx32/PSKoans#211]
# Describe "Koan Bug, Issue, or Help Request"

https://github.com/vexx32/PSKoans/blob/3070afd4200c997572ce5950bc91d44a1014d26f/PSKoans/Koans/Foundations/AboutComparison.Koans.ps1#L155

## Context "The Problematic Assertions"

I assume that this line is the example line, as line 156 includes the ___ to fill in the answer. 

-BeTrue 
should be:
 -Be $true

**Comment by EVWorth** [comment]
apparently -BeFalse and -BeTrue are an actual thing in pester?

It threw me off because -Be $true and -Be $false were being used before. Should this be standardized across all Koans one way or another?

**Comment by vexx32** [comment]
Yeah, the preference is for `-BeTrue` / `-BeFalse`. But at the same time, I don't expect folks to know that right out of the gates, which is why there's at least one `-Be $true` somewhere in there. I think having that as the first one might make more sense, and then (I hope) it should be clear enough to draw the connection to there being an actual parameter for that functionality?

Maybe it needs a comment. What do you think?

**Comment by EVWorth** [comment]
So are -BeTrue/-BeFalse wrapper properties for -Be $true/-Be $false?

Is there a reason to keep -Be $true/-Be $false, or would it make sense to replace it in all the Koans. I had to google a bit before I figured out that -BeFalse wasn't a typo.

**Comment by vexx32** [comment]
Not so much wrappers as they're just shorthand parameters for `Should` in Pester.

I would say we should keep only one `| Should -Be $true` (I think there's one right at the beginning of the koans?) and all the rest should use `-BeTrue` / `-BeFalse` as it's the more recommended pattern.

**Comment by EVWorth** [comment]
Ah I see here: https://github.com/pester/Pester/wiki/Should

So -Be is checking for equality to whatever comes after it, whether it be $true/$false, "Hello", 41, etc. 
-BeTrue/-BeFalse is specifically checking for $true/$false. 

I'll go ahead and close this as its correct in this example, but I'll submit PR's for instances of -Be $true/$false to be replaced by -BeTrue/-BeFalse.

Thanks!
