### ISSUE TITLE
Need a CONTRIBUTING.md

### ISSUE THREAD

**Issue by vexx32** [vexx32/PSKoans#215]
Currently we have little to no guidelines on preferred process of contributing, stylistic preferences (especially for the koan files themselves), etc.

Need to pull all those details into a CONTRIBUTING.md file so folks can be aware of how the repo operates.

If y'all have any suggestions of stuff that should go in there, let me know here so I can take it into account. ^^

**Comment by EVWorth** [comment]
I'm a big fan of MDT and when I saw this: https://github.com/FriendsOfMDT/PSD I wanted to get involved. Their [Contributing.md](https://github.com/FriendsOfMDT/PSD/blob/master/CONTRIBUTING.md) was really helpful in getting up and running with submitting pull requests, so I thought I'd use it as a template. I'll make a PR in a bit with something simple to start with and see what you think.

**Comment by vexx32** [comment]
Sounds good! Thank you! 😊

**Comment by petervandivier** [comment]
The MDT example-as-template is great; but the existing port of it in #217 ends up feeling like very "_boilerplate_" when reading though it. While it's super valuable to make guidance available for people new to git, github, and vscode, it's not until [nearly 200 lines in](https://github.com/vexx32/PSKoans/pull/217/files#diff-6a3371457528722a734f3c51d9238c13R193) that I found the first wording on how to contribute _specifically to this repo_.

Spitballing ideas (in increasing order of verbosity):
* remove most of the 200 line header & replace with a "see here for how to use GitHub" link. Keep contributing.md short and directly applicable to information that helps improve this repo
* split information on contributing into a couple different files. link as appropriate from the base contributing.md
* one-and-only-one contributing.md that provides a brief overview of the general topics and links off to a repo wiki for the individual topics in greater detail

hth, love the Koans 😄

**Comment by vexx32** [comment]
Yeah, I agree. I don't mind having some of the 'how to use git' stuff here, as having it close to hand can help, but it should probably be a separate file at the very least.

What do you think, @EVWorth?

**Comment by EVWorth** [comment]
I love the idea of utilizing the wiki. Especially using @petervandivier's third bullet point. 

I agree that it is super clunky to include the step by step guide to contributing in that document. I think it is a good idea to have it in some form though, as I imagine a lot of people using the koans who may want to contribute don't have much if any git experience. 

doing some research into the github wiki though, it seems by default, only [collaborators](https://help.github.com/en/articles/changing-access-permissions-for-wikis) can modify, and the only other option is to allow everyone to modify (not sure what approval controls are in place for that option)

If you don't want to go the wiki route, I can break out the boilerplate contributing stuff into its own .md file and link it.

**Comment by vexx32** [comment]
For now at least a separate MD fire should be sufficient. I have dug into how the GitHub wiki works much, but it might be worth looking into for the future. Thanks!
