### ISSUE TITLE
Adding more context for understanding Regex

### ISSUE THREAD

**Issue by EVWorth** [vexx32/PSKoans#218]
# Describe "Koan Bug, Issue, or Help Request"

https://github.com/vexx32/PSKoans/blob/09f013ca60e0d953d304391d9c654f31009162f9/PSKoans/Koans/Foundations/AboutStringOperators.Koans.ps1#L192-L201

## Context "The Problematic Assertions"

I feel like this could use a good bit more documentation/help for the user. 

I took me the better part of an hour to figure out what it was asking me to do for the $String = '____' section. 

while searching for an answer, I got a good bit of history, from [1997](https://stackoverflow.com/questions/10059673/named-regular-expression-group-pgroup-nameregexp-what-does-p-stand-for) no less!

In hindsight, I understand that `<FirstWord> <SecondWord>` are trying to point to creating a string with two words, and while I believe my understanding of regex has been expanded from trying to figure this out, something tells me that it wasn't meant to be that difficult. haha.

so, proposal! 

a simple addition:

`$Pattern = '^(?<FirstWord>[a-z]+) (?<SecondWord>[a-z]+)$' # How many words is this pattern looking for?`

To be clear, I am under the impression that the purpose of this "It" is simply to show how you can have multiple regex filters for multiple words (or whatever...), but I have no problem closing this issue without resolution if the intention was to make our brain's hurt for a little while. 😄

**Comment by vexx32** [comment]
Regex makes everyone's brain hurt the first few times. 😁 

Hmm, it could be better, I'm sure... 🤔 Not entirely sure an explicit comment is necessarily the way to go, but maybe?

@IISResetMe is there a more clear way to frame this one, do you think?

**Comment by IISResetMe** [comment]
Maybe split it into two tests? One that just gives a clear-cut example, and another one where we then flip the user-input:

```
# 1
It 'supports named matches' { 
    $String = 'PowerShell is rad' 
    $Pattern = '^(?<FirstWord>[a-z]+) [a-z]+ (?<LastWord>[a-z]+)$' 
 
    $Matches.FirstWord | Should -BeExactly '__'
    $Matches.LastWord | Should -BeExactly '__'
}
```

```
# 2
It 'supports named matches' { 
    $String = '__' 
    $Pattern = '^(?<FirstWord>[a-z]+) (?<SecondWord>[a-z]+)$' 
 
    $Matches.FirstWord | Should -BeExactly 'Cool'
    $Matches.SecondWord | Should -BeExactly 'Koans'
}
```
