### ISSUE TITLE
Abstracting Koan Answers

### ISSUE THREAD

**Issue by Sudoblark** [vexx32/PSKoans#226]
# Issue abstracting expected answer

Hi all! I've made a fork request to turn my PowerShell Intro Training course into PSKoans, in order to automate all the things. At the moment, I'm having difficulty in hiding a multi-choice answer in one of my PSKoans.

The issue is with the PSKoans\Koans\IntroTraining\WhatIsDotNet.koans.ps1 file in my fork.

## Context "The Problematic Assertions"

Importing the relative path of the answer module within each It block is OK:
```
       $RelativePath = ".\AnswerFunctions\IntroTraining\WhatIsDotNet\WhatIsDotNet.psd1"
        Import-Module $RelativePath
        # Replace __ with either 'jit' or 'compiled'
        '__'.ToLower() | Should -be (JitVsCompiled -Test arrivalOne).tolower()

```
But then when the user is prompted for answers they seek it tells them the answer rather than abstracting it:
```
Describing 'JIT or Compiled?' has damaged your karma.

    You have not yet reached enlightenment.

    The answers you seek...

Expected strings to be the same, but they were different.
Expected length: 3
Actual length:   2
Strings differ at index 0.
Expected: 'jit'
But was:  '__'
```

Which in the context of this koan, and future ones i want to implement, wouldn't be good! So if at all possible I'd just like some guidance on the best practice method of implementing this functionality.

## Context "Your Attempts"

The path is relative to the Koans directory, which is what the user is presented with when they meditate. I specifically created a separate module to contain functions to return answers in an effort to hide the expected answer.

I've searched all of the open and closed issues and can't seem to find anything relating to implementing multi-choice questions within PSKoans.

I've also done some reading up on pester unit testing and can't seem to find anything either, but that may be my newness to the technology.

## Context "Additional Information"

PowerShell Intro Course: https://github.com/Sudoblark/Powershell_Intro_Training
PSKoans Fork: https://github.com/Sudoblark/PSKoans 
Dev Branch: powershell_Intro_Port

**Comment by Sudoblark** [comment]
Update:
The following works:
```PowerShell
        $RelativePath = ".\AnswerFunctions\IntroTraining\WhatIsDotNet\WhatIsDotNet.psd1"
        Import-Module $RelativePath
        # Replace __ with either 'jit' or 'compiled'
        $Answer = '__'.ToLower() 
        if ($Answer -eq (JitVsCompiled -Test arrivalOne).tolower()) {

            $Answer | Should -Be (JitVsCompiled -Test arrivalOne).tolower()

        } else {

            $Answer | Should -be "Incorrect, please change your answer"
        }
```

But I feel like there's a better way to do this that I'm missing.

**Comment by vexx32** [comment]
A simpler option:

```ps
$Answer -eq (JitVsCompiled -Test arrivalOne) | Should -BeTrue -Because 'There is only one correct answer'
```

Note that unless you're doing case sensitive checks (or Should -BeExactly in the Pester syntax), you're not going to need the .ToLower() :)

**Comment by Sudoblark** [comment]
Ahah that's fantastic!

I've changed it to:
```PowerShell
        # Replace __ with either 'jit' or 'compiled'
        $Answer = '__'
        $Answer -eq (TestAnswers -Test arrivalOne) | Should -BeTrue `
        -Because "arrival-part_1 answer is either jit or compiled"
```

And it all works, plus much cleaner too! Knew i was being an idiot sandwich.

Thanks for the help. Looking forward to completing all the work i wanna do then submitting that pull request 😄

**Comment by vexx32** [comment]
With the `-Because` you might even be able to just drop the comment and let the user infer the information from the -Because statement. 🙂
