### ISSUE TITLE
Show-Karma -Meditate doesn't check the folder exists 

### ISSUE THREAD

**Issue by vexx32** [vexx32/PSKoans#256]
# Describe "Module Bug or Issue"

Executing `Show-Karma -Meditate` before the first run does not first check to see if the koans folder actually exists first.

## Context "The Problem"

There is no check in the code for whether the folder exists.

https://github.com/vexx32/PSKoans/blob/da66f062c93dca112214016285b2bd5891eb87c5/PSKoans/Public/Show-Karma.ps1#L45-L66

## Context "Expected Behavior"

The command should behave similarly to the standard `Show-Karma` behaviour, where it checks for the folder's existence. If it does not exist, it should execute `Update-PSKoan` the same way that the default (parameterless) behaviour does.

## Context "Additional Information"

```powershell
Name    Version
----    -------
PSKoans 0.50.1
PSKoans 0.50.0
PSKoans 0.42.2

Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by usrme** [comment]
I'll have a crack at this if that's okay! 🖐

**Comment by vexx32** [comment]
It's all yours! 😊
