### ISSUE TITLE
Show-Advice -Name requires the full basename

### ISSUE THREAD

**Issue by vexx32** [vexx32/PSKoans#261]
# Describe "Module Bug or Issue"

## Context "The Problem"

Unlike with `Show-Karma -Topic <name>`, `Show-Advice -Name <name>`  requires the topic name to include the `.Advice` suffic (`Show-Karma` doesn't expect the `.Koans` suffix to be included).

It also does not support tab completion the same way that Show-Karma's -Topic parameter does.

## Context "Expected Behavior"

`Get-Advice -Name Profile` should show the `Profile.Advice.json` snippet.

**Comment by usrme** [comment]
I'll grab this one as well! 🙊

**Comment by vexx32** [comment]
All yours! 😊

**Comment by usrme** [comment]
Might I suggest breaking out the tab completion difference in functionality to a separate issue?

**Comment by usrme** [comment]
Ah, okay! Let's keep this to just one issue then 👍
