### ISSUE TITLE
Show-Karma -Meditate not opening VSCode properly

### ISSUE THREAD

**Issue by robdy** [vexx32/PSKoans#284]
# Describe "Module Bug or Issue"

I have VSCode installed on my machine. I noticed that when I run `Show-Karma -Meditate`, it doesn't open the folder properly. Instead, it opens `.\~\PSKoans` file (non-existing). You can see that behavior on the screenshot:

![2019-10-10 21_47_52-● PSKoans - Visual Studio Code](https://user-images.githubusercontent.com/15113729/66601331-f2f94900-eba7-11e9-971c-de27257ae7a0.png)

## Context "The Problem"

I cloned the repo directly from GitHub, added the folder to `$env:PSModulePath`, run `Show-Karma` and then, as per the instruction, run `-Meditate`.

The issue sounds to be here:

https://github.com/vexx32/PSKoans/blob/3fb8b44ac9e4d79daec480d397818c4b7a6caa9b/PSKoans/Public/Show-Karma.ps1#L78-L83

In my case, if I change it to this (to use full folder path instead):

```powershell
 $VSCodeSplat = @{ 
     FilePath     = 'code' 
     ArgumentList = '"{0}"' -f (Get-Item (Get-PSKoanLocation)).FullName
     NoNewWindow  = $true 
 } 
 Start-Process @VSCodeSplat 
```
it works correctly:
![image](https://user-images.githubusercontent.com/15113729/66601769-f3461400-eba8-11e9-8e82-ef42614a040e.png)

## Context "Expected Behavior"

I expect the folder to be opened in VSCode.

## Context "Additional Information"

```powershell
PS C:\Users\robdy> Get-Module -Name PSKoans -ListAvailable |
>>     Select-Object -Property Name, Version

Name    Version
----    -------
PSKoans 0.50.1


PS C:\Users\robdy>
PS C:\Users\robdy> $PSVersionTable | Out-String

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I can open PR to address this, as described above. Alternatively, I can change `Get-PSKoanLocation` to return full path.

**Comment by vexx32** [comment]
🤔 Is this in the module version currently on the gallery?

This may have been fixed already... @indented-automation did you take care of this one at some point?

**Comment by robdy** [comment]
@vexx32 I used the version from GitHub, not from Gallery

**Comment by vexx32** [comment]
👍 There may have only been a partial fix, then. If you want to fix it, go right ahead. 💖
