### ISSUE TITLE
Show-Karma -Meditate doesn't open editor correctly when a space exists in user path

### ISSUE THREAD

**Issue by camusicjunkie** [vexx32/PSKoans#306]
# Describe "Module Bug or Issue"

Show-Karma -Meditate doesn't open editor correctly when a space exists in user path

## Context "The Problem"

My user folder contains a space so when `Show-Karma -Meditate` runs it opens a folder path that doesn't exist. `Start-Process` doesn't allow for a space in the path unless it's properly quoted.

## Context "Expected Behavior"

The koan folder should open to the correct folder.

## Context "Additional Information"

```powershell
Show-Karma -Meditate
```

**Comment by vexx32** [comment]
Had a quick look, seems pretty simple. I'll take care of it for now; I'm planning on doing a quick bugfix release in a day or two to take care of the few remaining problems here and there. 🙂

**Comment by camusicjunkie** [comment]
Sweet!
I just added the escaped quotes `ArgumentList = '"', $PSKoanLocationFullPath, '"'` to resolve it for me.
