### ISSUE TITLE
Problem with the installation instructions

### ISSUE THREAD

**Issue by sideh** [vexx32/PSKoans#31]
Hello,

I am having trouble following some instruction as they expected outcome does not occur. I assume that some update must have changed the way it was meant to work.

Double click on the PSKoans.psm1 file, and VS Code will launch a powershell console

When I double click this file in the Visual Studio Code it just opens it for me to read and edit the code not actually run it.

Thanks,

**Comment by vexx32** [comment]
It hasn't changed all that much... But I do need to update my instructions!

In the VS Code terminal, import the module file
```powershell
Import-Module C:\path\to\module\PSKoans\PSKoans.psd1
```
And then call the `rake` command to set things up. From there, call `rake -Meditate` to open the folder with the koans for you to edit.

I'll leave this issue open until I fix the instructions in the readme, either tonight or tomorrow. :)

**Comment by vexx32** [comment]
Got it uploaded to gallery & updated readme :D
