### ISSUE TITLE
Issue with AboutAssertions

### ISSUE THREAD

**Issue by arefg** [vexx32/PSKoans#315]
Hi Joel 😃 
Great job with the new version 👍 
I wasn't around lately, I read on twitter about the new version, so I'm going to go through it from the beginning and give you a headake every now and then 😉 
so for the first one:
I found this by chance and I think this is an issue with pester test itself because even if I leave the last It block untouched the test will pass somehow. 🤔 I couldn't find this behavior somewhere else yet.

 It 'demands balance' {
        # Both sides of the scale must be of equal measure.
        __ + 2 -eq 3 | Should -BeTrue
    }

**Comment by arefg** [comment]
Sorry, I forgot to mention the file name. It's in the AboutAssertions file.

**Comment by vexx32** [comment]
Ah, I should have noticed that one. Thanks for bringing it up!

Yeah, unfortunate behaviour from casting the blank object there.... Hmm. Couple ways I could fix that, I'll have to see what works best :)
