### ISSUE TITLE
Enable syncing of PSKoans to alternate locations

### ISSUE THREAD

**Issue by figueroadavid** [vexx32/PSKoans#325]
# Describe "Functionality"
I would like PSkoans to be able to sync to a different location instead of just the user profile.  I.e. dropbox, google drive, network location, etc.  

I use multiple computers frequently, and the PSKoans are tied to the specific user profile on the specific machine.  So, I end up having to either use them all from a single machine or manually sync them.  If the PSKoans could either be sync'd to a different location or stored in a different location automatically, that would make this substantially easier. 

Easiest: Allow them to be placed in a different location on the system, this would allow users to store them in a sync'd location like C:\Dropbox, and then they would automatically be available on other systems.

Harder: Implement direct syncs to 3rd party cloud providers; this could be a plugin type of architecture.

## Context "Private or Public? What are the use cases? Parameters? Options?"
Public.  

The use case is anyone that wants to use PSKoans on multiple systems. 

## Context "Additional Information"
I could see this being supported by adding another command or two to PSKoans
`Set-PSKoansHome`, `Move-PSKoans`, `Set-PSKoansSyncProvider` etc..

**Comment by vexx32** [comment]
`Set-PSKoanLocation` is available currently 😁 

I do like the idea for `Move-PSKoanLocation` or something in that vein though, so you don't need to manually move your files after changing the location.
