### ISSUE TITLE
Misspelling in AboutBinaryKoans

### ISSUE THREAD

**Issue by JeffChristman** [vexx32/PSKoans#326]
# Describe "Koan Bug, Issue, or Help Request"
AboutBinaryKoans.ps1

Misspelling in the comment section of About binary koan.

Line 17 - "`What is represents is a base 2 number`."

Should Be - "What _it_ represents is a base 2 number."

**Comment by vexx32** [comment]
Thanks for reporting this! I'll take care of it in my next pass of this file, if it doesn't get done sooner. 😊

**Comment by ArtisanByteCrafter** [comment]
I took care of it, had a few minutes :)
