### ISSUE TITLE
Commented line displays 14 but code converts 7

### ISSUE THREAD

**Issue by JeffChristman** [vexx32/PSKoans#331]
# Describe "Koan Bug, Issue, or Help Request"
In **AboutBinary.Koans.ps1,** the comment does not match the expected output

Line # 127 through 130
_________________________
```
# Replace __ with the binary value of 14
$Binary = "01110" 
$Value = 7
$Value | Should -Be ([Convert]::ToInt32($Binary, 2))
```

$Value should be equal to 14, not 7 to coincide with the commented line

**Comment by JeffChristman** [comment]
I just checked the original source code in the repo. It is correct in the repo. I must have inadvertently made a type while I was going through the lesson

**Comment by vexx32** [comment]
@JeffChristman it may have been fixed recently-ish. If you run across things like this in future, you can:

1. Make sure your module is up to date (`Update-Module PSKoans`)
2. Run `Update-PSKoan` to ensure your local koan library is as up to date as possible (this will make sure changes that add or remove entire koan `It` blocks are copied across).
3. Check that your copy of the koan is up to date by resetting that koan to the same fresh state stored in the PSKoans module itself: `Update-PSKoan -Topic $topicName -Name $itBlockName`
