### ISSUE TITLE
AboutDiscovery.Koans.ps1 Get-Help does not account for PS Version

### ISSUE THREAD

**Issue by figueroadavid** [vexx32/PSKoans#332]
# Describe "Functionality"
The first section of AboutDiscovery does not reflect the version of Powershell in use.  
The code segment is on line 33
```powershell
$GetHelpParams | Should -Be @(
    'Category'
    'Component'
    '__'
    'Examples'
    '__'
    '__'
    'Name'
    'Online'
    '__'
    'Path'
    'Role'
    '__'
)
```
The issue is that the list of parameter names is different between Windows PS and PS Core.  The `ShowWindow` parameter does not exist in PS Core.  If possible, the ideal situation would be for the Koan to take into account the PS version used.   A non-windows machine would not have the ability to discover the `ShowWindow` parameter, and the Koan fails if it is not present.  

## Context "Private or Public? What are the use cases? Parameters? Options?"
Public context. 

## Context "Additional Information"
Correct answer for PS 5.1 (and potentially earlier)
```powershell
$GetHelpParams | Should -Be @(
	'Category'
	'Component'
	'Detailed'
	'Examples'
	'Full'
	'Functionality'
	'Name'
	'Online'
	'Parameter'
	'Path'
	'Role'
	'ShowWindow'
)
```
Correct answer for PS 6+
```powershell
$GetHelpParams | Should -Be @(
	'Category'
	'Component'
	'Detailed'
	'Examples'
	'Full'
	'Functionality'
	'Name'
	'Online'
	'Parameter'
	'Path'
	'Role'
#	'__'
)
```

I realize the Koan is not version specific and could be accessed from different versions.  Ideally, the testing would take this into account depending on which version is being used to run the test, or at least a note that the answer is different between WinPS & PSCore.

**Comment by vexx32** [comment]
This issue is also mentioned in https://github.com/vexx32/PSKoans/issues/234 and was partially resolved with #270.

This could definitely be called out better and specific note made of the version / OS differences.
