### ISSUE TITLE
Foundations/AboutAssignmentAndArithmetic.Koans

### ISSUE THREAD

**Issue by scottone** [vexx32/PSKoans#334]
# Describe "Koan Bug, Issue, or Help Request"

Foundations/AboutAssignmentAndArithmetic.Koans.ps1

## Context "The Problematic Assertions"

There are now 6 It blocks in this block:
Describe 'Assignment/Arithmetic Combination Operators'
Blocks 1, 2, 6 assign an integer to $Value before the code that applies the operator.
Blocks 3,4,5 (see below) do not, and the scoping of the IT blocks caught me off-guard.
My instinct was to assume that $Value was global to the Describe.
The previous version of this Koan put all assertions into a single IT block, which is good since the student has not yet studied the concept of scope.

Note: block 4 has no work for the student.

My suggestion is to set $Value in each It block as done in the first 2, 
perhaps:
``` $Value = 12```

```
#block3
It 'is also possible to combine subtraction with assignment' {
        $Value -= 3
        __ | Should -Be $Value
    }

#block4   
   It 'works the same way with division' {
        $Value /= 2
        $Value | Should -Be 8
    }

#block5
    It 'works with multiplication as well' {
        $Value *= 3
        __ | Should -Be $Value
```

**Comment by vexx32** [comment]
Yeah, looks like I overlooked block 4... and those others should all set their own `$Value` rather than "borrowing" from the previous ones. Good catch! 💖
