### ISSUE TITLE
Cmdlets1\AboutDiscovery.ps1

### ISSUE THREAD

**Issue by scottone** [vexx32/PSKoans#335]
# Describe "Koan Bug, Issue, or Help Request"

## Context "The Problematic Assertions"
```
It 'can look for commands by module' {
        $KoanCommands = Get-Command -Module 'PSKoans' |
            Sort-Object -Property Name
        $First4Commands = $KoanCommands | Select-Object -First 4

        __ | Should -Be $KoanCommands.Count
        @('__', '____', '____', '____') | Should -Be $KoanCommands.Name
    }
```
## Context "Your Attempts"
The assertion could only pass if there were 4 commands in the PSKoans module.
Correction:
`@('__', '____', '____', '____') | Should -Be $First4Commands.Name`

**Comment by vexx32** [comment]
Whoops, good catch! Feel like we should have seen that one before 😅
