### ISSUE TITLE
Backup/Restore Pester module; PSKoans uninstall and cleanup instructions

### ISSUE THREAD

**Issue by Treasure-Box** [vexx32/PSKoans#336]
# Backup/Restore existing Pester module; PSKoans uninstall and cleanup instructions

## Instructions or a separate script should be provided regarding the steps needed to backup/restore the build-in Pester module, and the process of uninstalling the PSKoans module and the files it adds to the user profile to restore the system to a pre-PSKoans state.

**Comment by vexx32** [comment]
There are two ways we could go about this.

One is to simply provide a short script as part of the README file that can do these functions. Another would be to create a more comprehensive and robust function that ships as part of the module.

Not sure what's best for that at this point in time 🤔
