### ISSUE TITLE
1 maybe 2 issues with 'AboutMeasureObject.Koans.ps1'

### ISSUE THREAD

**Issue by JoeWatts** [vexx32/PSKoans#340]
**ISSUE 1:**  'can operate on object properties' 

Well Averages can be challenging especially when the resulting average can have a seemingly endless number of significant digits.  I would propose that you limit the number of significant digits in some manner otherwise it is going to be hit and miss for passing this test. 

**Original Line 80:**

__ | Should -Be $Data.Average

**Modified Line 80:**

__ | Should -Be Should -Be ([math]::Round($Data.Average,4))

**ISSUE 2:** 'can measure text lines, characters, and words of strings'

**EXCEPT** when the file does not exist, then the answers are always zero (0).  If this was your intent then this isn't an issue, otherwise it might be wise to have a file that exists as part of the data.  I just picked a file and plugged it in.

**Original line 84:**

$Text = Get-Content "$(Get-PSKoanLocation)/Foundations/AboutTheStockChallenge.Koans.ps1"

**Modified line 84**

Depends on the intent of the developers.

**Comment by vexx32** [comment]
Yeah, agreed on the rounding issue. For the latter point, it might be a better call to simply include a few lines of text in the koan file itself rather than trying to read another file.

**Comment by JoeWatts** [comment]
How about this for a modification to line 84

$Text = Get-Content $PSCommandPath

This may have some folk scratching their heads, until they google it, of course.
