### ISSUE TITLE
Issues with 'AboutTeeObject.Koans.ps1

### ISSUE THREAD

**Issue by JoeWatts** [vexx32/PSKoans#341]
**ISSUE 1**  'can store the object(s) into a variable'

**Original Line 22**

$Values = 'alpha', 'beta', 'gamma'
@(  '`____`', '`____`', '`____`', '`____`') | Tee-Object -Variable 'Numbers' | Should -Be $Values

**Modified Line 22**

$Values = 'alpha', 'beta', 'gamma'
@(  '`____`', '`____`', '`____`') | Tee-Object -Variable 'Numbers' | Should -Be $Values

Once again depending on the intent of the developer.  

If the intent was to only supply enough slots for the values located in $Values then there needs to be one **less** placeholder.
If the intent is to keep the individual working through the tests on their toes so they realize that there is one too many place holders then this is good to go.  However, you may have folk searching the Issues to see if this has been reported.

**ISSUE 2** 'can also store the object(s) into a file'

**Original Line 33**

@( '`__`','`__`','3','`__`','`__`') | Should -Be $Stored

**Modified Line 33 and add a line 34**

@('`__`','`__`', '0.33', '`__`','`__`',) | Should -Be $Stored
Remove-Item -$File -Force -ErrorAction SilentlyContinue

When dividing 1 by a number the only way to get a whole number is to divide by 1,  All other values are going to be fractions, so a whole value of 3 doesn't work
Also we really should be good citizens and clean up after ourselves.

**Comment by vexx32** [comment]
Thanks for submitting this! These all look like good changes to make. Thanks! 😊
