### ISSUE TITLE
AboutStringBuilder - Mismatched Variables

### ISSUE THREAD

**Issue by JoeWatts** [vexx32/PSKoans#367]
### Mismatched Variables
This has already been addressed in Issue #188, but #188 is closed, and it isn't fixed. On the upside this is the only issue I found in this Koan.

160   $ExpectedCount = $Properties |
161   Measure-Object |
162   Select-Object -ExpandProperty Count
163
164  $PropertyCount | Should -Be $ExpectedPropertyCount

At line 160, $ExpectedCount is initialized 
A comparison is made at line 164 with $ExpectedPropertyCount

The variable needs to synchronized.

**Comment by vexx32** [comment]
Good catch! Thanks for reporting this! It's a pretty quick fix, I'll see if I can get a moment to take care of it this week. If you or anyone else would like to submit a PR for it before I get to it, you're more than welcome to. 😊 💖

**Comment by Maamue** [comment]
This issue can be closed @vexx32, apparently I mistyped the issue number and prevented it from autoclosing?

**Comment by vexx32** [comment]
Ah yeah, I didn't see that. Thanks!
