### ISSUE TITLE
Add Topic - AboutClasses

### ISSUE THREAD

**Issue by rdbartram** [vexx32/PSKoans#37]
demonstrate how to create classes. How properties and methods works, access modifiers (hidden), inheritance etc. I wouldn't mind chipping in if it's something you want in the project

**Comment by vexx32** [comment]
This would be great! I think this should probably go somewhere in the Advanced Techniques folder, as classes aren't in super common use in PS?

One thing I think should definitely be covered is the use of classes to implement custom attributes, especially as it relates to custom parameter validation; Kevin Marquette has a great blog post on it. May want to also touch on enums as well!

I'd love to see what you can come up with! And of course I'll be happy to offer any suggestions or help I can give :D

**Comment by PeterMTaylor** [comment]
especially how to use classes with Pester. Pity the order of loading the classes must be in memory first before invoking Pester.

**Comment by rdbartram** [comment]
Thanks! I'll do that.
