### ISSUE TITLE
Issues with AboutEnumeration

### ISSUE THREAD

**Issue by JoeWatts** [vexx32/PSKoans#372]
### First issue

Issue #369, still seems to be broken,  I tried the Update-Koans,  I even copied directly from the Git Repository,  still broken.   So to fix "You are already in a test case." issue

At line 112 add a "}"
At line 628 remove a "}"

That was lots of fun to find! (head shaking)

### Second Issue
The following code, found at line 228, is not going to compile unless you are using Powershell Core 6.2.0 or better, and the Skip command in the test doesn't keep it from compiling

`enum Int64Enum : Int64 { LargeValue = 9223370000000000000 }`

I couldn't get it to work with Powershell Core 7.0 either, but I didn't try very hard.

I simply removed the test "It 'can represent other integer in PowerShell Core'" from the Koan and kept on rolling.  

It is a cool concept that you are introducing but unless you are going to force using Powershell Core 6.2.0 or better, it may not be worth hanging on to.

### Third Issue

At line 286, the [Enum]::TryParse is being used incorrectly,  the $enumType is not needed 
The code should be corrected to 
`$result = [Enum]::TryParse( $valueToParse, [Ref]$parseResult)`

**Comment by vexx32** [comment]
> First issue

Yep, that's... wow, that looks like a real pain to find. Well done, and thankyou! I'll get that one fixed.

> Second issue

Yeah, I see the logic error there. That should be a string, not a scriptblock, and convert just before it's used. 

> Third issue

Hmm... I don't think so. The overload definitions for `[Enum]::TryParse()` are:
```
OverloadDefinitions
-------------------
static bool TryParse(type enumType, string value, [ref] System.Object result)
static bool TryParse(type enumType, string value, bool ignoreCase, [ref] System.Object result)
static bool TryParse[TEnum](string value, [ref] TEnum result)
static bool TryParse[TEnum](string value, bool ignoreCase, [ref] TEnum result)
```

The overload you're suggesting we use there is a generic method, and that call is very fragile -- if a variable containing a value of the wrong type is used as the `[ref]` (including a variable that has no value / is set to `$null`), that's not going to be resolvable.

Specifying the type with the other overload is a better bet, I think; it's too easy to have it fail otherwise. It's not incorrect, by any means, it's just a different overload for the method. 🙂

**Comment by vexx32** [comment]
Hmm, looks like the additional overloads _are_ indeed missing in Windows PowerShell. I wasn't aware they were actually quite new. I'll have a look at what we can do there...

**Comment by vexx32** [comment]
@indented-automation do you have any suggestions on that last point?

Code is here:
https://github.com/vexx32/PSKoans/blob/1a0fb29d0a557837ffe34d4fd3c3120fce21f03e/PSKoans/Koans/Constructs%20and%20Patterns/AboutEnumerations.Koans.ps1#L261-L290

The two overloads that take a specific `[type]` object in .NET Core are missing in Windows PowerShell. 😕

**Comment by JoeWatts** [comment]
I agree that the untyped TryParse is fragile,  I suppose that I should have mentioned that I had gone looking for the additional overload definitions, and was unable to locate them. I suppose this is the excitement of working through these things, when the environment is so highly dynamic.

Looking forward to seeing what  @indented-automation  has to say.

**Comment by vexx32** [comment]
That's one option, but I don't think that TryParse method is any more specific... I had a quick look at that, but unless I missed something, it looks like it just inherits the same fragile methods from Enum itself.

That said, provided the variable you're passing in as reference is of the right Enum type, it'll still work okay.

**Comment by vexx32** [comment]
Might be worth an added note that you have to pass in a variable that already contains one of the enum values for it to work as well, but yep! 😄
