### ISSUE TITLE
Unit test the answers

### ISSUE THREAD

**Issue by rdbartram** [vexx32/PSKoans#39]
Maybe we should include the answers somewhere in the project but not publish them with the module in the gallery. This way we can find bugs in the koans before we push. Thoughts?

**Comment by vexx32** [comment]
So, essentially, you want to keep a copy of the 'complete' koan files in the repo so we can run them as actual tests before we ship the 'incomplete' ones with the actual module?

That's not a bad idea, but it being around as part of the repo might encourage some folks to just... skip actually doing them :/

If there's another relatively straightforward way to check that, for example, the koans are failing in *only* the method we intend, that might perhaps be a better route? What do you think?

**Comment by rdbartram** [comment]
to some extent I think If people are willing to go to the repo and cheat then its there own fault. Maybe I can come up with a way that we wouldn't need to keep a complete copy of the koans, perhaps just write unit tests that dynamically update the values in the koans to make sure they fail and pass when they should.

**Comment by vexx32** [comment]
That's probably going to have to run into way too much self-testing I think. 

Hmm. @steviecoaster your thoughts, friend?

**Comment by steviecoaster** [comment]
Agreed. That's going to create a mountain of work.

**Comment by rdbartram** [comment]
OK it was just a suggestion. I guess I can close this issue now. I'll just finish going the koans and correct any issues I find.
