### ISSUE TITLE
Pester 5.0.0 installed and the module is loading correctly, but no koan errors ever get caught

### ISSUE THREAD

**Issue by IarwainBen-adar** [vexx32/PSKoans#391]
# Describe "Module Bug or Issue"

I followed [the official Pester instructions](https://pester.dev/docs/introduction/installation) to upgrade Windows 10's preinstalled copy of Pester 3.4.0 to the latest version 5.0.0. Then I installed PSKoans via `Install-Module Pester -Scope CurrentUser`. However, when I run `Show-Karma`, the PSKoans module seems to think all koans have been completed (examining for example `AboutAssertions.Koans.ps1` shows this clearly to be false). Any run of `Show-Karma` results in the following output:
```none
    Welcome, seeker of enlightenment.
    Please wait a moment while we examine your karma...

    Congratulations! You have taken the first steps towards enlightenment.

    You have completed:

    You cast your gaze back upon the path that you have walked...

 [―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――] 0/678
```
Obviously that score of `0/678` shows that nothing has been completed, but Pester doesn't seem to catch any of the errors, either.

## Context "The Problem"

I'm just trying to take a look at PSKoans because it seems like an interesting set of exercises, but somehow Pester is not catching the errors.

## Context "Expected Behavior"

I expected to see `You have not yet reached enlightenment` and various error output to investigate.

## Context "Additional Information"

```powershell
Get-Module -Name PSKoans -ListAvailable |
    Select-Object -Property Name, Version

Name    Version
----    -------
PSKoans 0.66.2

$PSVersionTable | Out-String

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-Module -Name Pester

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     5.0.0                 Pester                              {Add-ShouldOperator, AfterAll, AfterEach, Assert-MockCalled…}
```

**Comment by vexx32** [comment]
I'd venture to guess this is _mainly_ due to the fact that the Pester result object format/structure has changed in v5.0.

This is fixable, I'd imagine, just needs someone to take a look at the differences and branch the path for pester v5 off the main path here.

I'll mark this up for grabs for now, but I'll circle back to it probably within a week or so if nobody else is jumping at the bit to do it themselves. 🙂
