### ISSUE TITLE
Koan uses file length that can change breaking Koan

### ISSUE THREAD

**Issue by ThomasNieto** [vexx32/PSKoans#414]
# Describe "Koan Bug, Issue, or Help Request"

Foundations/AboutConditionals.Koans.ps1 - 'can be used to select a value for a variable'

## Context "The Problematic Assertions"

```powershell
function Get-Thing {
    return (Get-ChildItem -Path $HOME -File | Select-Object -First 1).Length
}
```

## Context "Your Attempts"

Koan will pass but running it a different time after the length has changed breaks the Koan.

## Context "Additional Information"

The Koan should not use information that is dynamic on the system as the value can change causing the Koan to pass or fail randomly.

**Comment by vexx32** [comment]
Similar idea to #183, I think? 🙂

**Comment by ThomasNieto** [comment]
I think using Pester's `TempDrive` would be the best since it gets cleaned up after each run and is constant.

**Comment by vexx32** [comment]
It would be, just means the koans themselves need to do additional setup to make it work. I suppose that's ultimately fine, though.
