### ISSUE TITLE
Powershell Core 7.1.2 Exception importing PSKoans module

### ISSUE THREAD

**Issue by rogerramtech** [vexx32/PSKoans#426]
# Describe "Module Bug or Issue"
No longer able to import PSKoans module.  Pester imports no problem. 
'Exception: Assertion operator name 'Be' has been added multiple times.`

## Context "The Problem"
Using PS Core 7.1.2 on MACOS Big Sur.
```powershell
install-module Pester
install-module PSKoans -Force

Exception: Assertion operator name 'Be' has been added multiple times.
```

Was working previously before upgrade to Big Sur.  I am not certain that this was the catalyst though.  may have worked afterwards also.
Currently cannot load the module anymore.  Tried rolling back to PSCore 7.1.1 with same outcome.
Also happened previously.  Prior to loading BigSur, but went away with no apparent changes to system.

## Context "Expected Behavior"
Should load module and work correctly.

## Context "Additional Information"

```powershell
Get-Module -Name PSKoans -ListAvailable |
    Select-Object -Property Name, Version

Name    Version
----    -------
PSKoans 0.67.1

$PSVersionTable | Out-String

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
To my memory, we expect and explicitly catch that exception just in case. This is happening on a completely fresh shell as well? Just importing the module?

What version(s) of Pester do you have installed?

**Comment by rogerramtech** [comment]
Yes.  Happening in Fresh shell.
Restarted entire computer even.
```
gmo | select Name, Version

Name                              Version
----                              -------
Microsoft.PowerShell.Management   7.0.0.0
Microsoft.PowerShell.Utility      7.0.0.0
Pester                            5.1.1
PowerShellEditorServices.Commands 0.2.0
PowerShellEditorServices.VSCode   0.2.0
PSReadLine                        2.1.0
```
Interestingly, I have 2 shells running.  1 in iTerm2 and one in the VS Code Terminal.
When I created the issue before, neither would work.  Immediately after creating the issue, I ran 
`ipmo PSKoans -Verbose`
and it loaded!  No issue.
However the one running in the Code Terminal will not import still.
```
ipmo PSKoans -Debug -Verbose             

VERBOSE: Loading module from path '/Users/ross/.local/share/powershell/Modules/PSKoans/0.67.1/PSKoans.psd1'.
Exception: Assertion operator name 'Be' has been added multiple times.
```

**Comment by rogerramtech** [comment]
## Temporary Solution
Looks to be a intermittent Pester version incompatibility issue.  Loaded 4.10.1 and all is well again.

(Long hand for clarity, for anyone else having the issue)
```powershell
Remove-Module -Name Pester
Install-Module -Name Pester -RequiredVersion 4.10.1
Import-Module -Name Pester -RequiredVersion 4.10.1
Import-Module -Name PSKoans
Get-Module | Select-Object -Property Name, Version         


Name                              Version
----                              -------
DummyTypes                        0.0
Microsoft.PowerShell.Management   7.0.0.0
Microsoft.PowerShell.Utility      7.0.0.0
PackageManagement                 1.4.7
Pester                            4.10.1
PowerShellEditorServices.Commands 0.2.0
PowerShellEditorServices.VSCode   0.2.0
PowerShellGet                     2.2.5
PSKoans                           0.67.1
PSReadLine                        2.1.0

$PSVersionTable | Out-String

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
That's really weird... Not really sure what would _cause_ that, other than probably Pester being loaded multiple times for some reason.

**Comment by vexx32** [comment]
I'll close this for now as it seems to be resolved and there is something of a solution. If you see it again, feel free to update this issue and maybe there's something we can do here in future when we know more.

**Comment by rogerramtech** [comment]
Thanks!  I appreciate the nudge in the right direction and assistance.
Pester does not appear to be loaded multiple times according to Pwsh, but... Who knows.
Any idea on time frame of v5 compatible version?

**Comment by vexx32** [comment]
I'd like to get a few more things sorted before I publish it, but the current main branch here is v5 compatible, from memory. Just some loose ends to tie up, really. The main thing that made me hesitate is that due to how one of the functions works, we can't test its functionality using Pester itself, which is a bit annoying, I'd like to confirm it works correctly, after all... 

But perhaps it's waited long enough 🙂
