### ISSUE TITLE
Undesired error with unresolved koan AboutPSProviders

### ISSUE THREAD

**Issue by peetrike** [vexx32/PSKoans#434]
# Describe "Koan Bug, Issue, or Help Request"

```powershell
Show-Karma -Topic AboutPSProviders
```
emits following error:
```
Invoke-Koan: C:\Program Files\WindowsPowerShell\Modules\PSKoans\0.67.1\Public\Get-Karma.ps1:111
Line |
 111 |                  $PesterTests = Invoke-Koan @{
     |                                 ~~~~~~~~~~~~~~
     | This command cannot find a matching alias because an alias with the definition '____' does not exist.
```
The error appears with both PowerShell 7 and 5.1

## Context "The Problematic Assertions"

The problem is with line https://github.com/vexx32/PSKoans/blob/c1ad5c98d63d0dbe02a50d4dd56d6a7fd5923810/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L78

as soon as previous line gets correct cmdlet name, the error ceases to exist.

It would be good idea to add -ErrorAction SilentlyContinue to Get-Alias on that line.

**Comment by vexx32** [comment]
Huh, haven't seen this come up before. Strange. Thanks for reporting, should be fairly straightforward to fix.
