### ISSUE TITLE
Bug in koan AboutPSProviders

### ISSUE THREAD

**Issue by peetrike** [vexx32/PSKoans#435]
# Describe "Koan Bug, Issue, or Help Request"

As soon as It block 'allows access to variables in the current scope' becomes resolved, the next block throws an error:
```
Invoke-Koan: C:\Program Files\WindowsPowerShell\Modules\PSKoans\0.67.1\Public\Get-Karma.ps1:111
Line |
 111 |                  $PesterTests = Invoke-Koan @{
     |                                 ~~~~~~~~~~~~~~
     | Cannot remove variable Test because the variable has been optimized and is not removable. Try using
     | the Remove-Variable cmdlet (without any aliases), or dot-sourcing the command that you are using to
     | remove the variable.
```
The error occurs in both PowerShell 5.1 and 7.1

## Context "The Problematic Assertions"

The error occurs on line: https://github.com/vexx32/PSKoans/blob/c1ad5c98d63d0dbe02a50d4dd56d6a7fd5923810/PSKoans/Koans/Cmdlets%201/AboutPSProviders.Koans.ps1#L261

## Context "Your Attempts"

Renaming variable to something else doesn't help.  But it helps, when the used variable name is conditionally deleted (if exists) in the beginning of the It block.  Something like:
```powershell
if (Test-Path -Path 'Variable:Test') {
    Remove-Variable -Name 'Test'
}
```

## Context "Additional Information"

It seems to be a scoping issue, but can't understand, from where the variable gets inserted.  Especially when unique name is assigned to variable.

**Comment by peetrike** [comment]
the problem doesn't occur, when this It block appears as original (or has been reset).  As soon as I add first answer, the problem occurs

**Comment by vexx32** [comment]
Hmm. Okay, yeah. I think the core of the issue is that the `$Test` variable originally is created in a prior `It` block. Seems like PowerShell is treating that as optimized or something.

I think this can be worked around by changing the variable name used in the problematic assertion there.

**Comment by peetrike** [comment]
I tried to use another name for the variable in that block.  The problem appeared as with old name.

At the same time, that problem doesn't occur when I take the code in block and run it in separate PowerShell session
