### ISSUE TITLE
Recursion on $home throws UnauthorizedAccessException - Local Issue

### ISSUE THREAD

**Issue by DEberhardt** [vexx32/PSKoans#456]
# Describe "Koan Bug, Issue, or Help Request"

AboutMeasureObject.Koans.ps1

## Context "The Problematic Assertions"

```powershell
Describe 'Measure-Object' {
    BeforeAll {
        $Numbers = @(
            839, 339, 763, 663, 238, 427, 577, 613, 284, 453
            850, 130, 250, 843, 669, 972, 572, 41, 172, 155
            729, 616, 285, 231, 128, 540, 204, 584, 407, 98
            668, 85, 320, 435, 87, 719, 936, 25, 75, 122
            665, 154, 943, 35, 391, 816, 420, 229, 3, 938
        )

        $Files = Get-ChildItem -Path $HOME -Recurse -Depth 2
    }
```

Line 20 ($Files = ...) fails for me with:
```powershell
Invoke-Koan : Access to the path 'C:\Users\David\Intel\Logs' is denied.
At C:\Users\David\Documents\WindowsPowerShell\Modules\PSKoans\0.67.1\Public\Get-Karm
a.ps1:111 char:32
+                 $PesterTests = Invoke-Koan @{
+                                ~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\David\Intel\Logs:String)
   [Invoke-Koan], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Invoke-Koan

```

## Context "Your Attempts"

removed recursion to avoid unauthorizedAccessEception:
`$Files = Get-ChildItem -Path $HOME #-Recurse -Depth 2`

## Context "Additional Information"

None

**Comment by DEberhardt** [comment]
same in `AboutWhereObject.Kaons.ps1`

It 'also missing 3d vision ;)' {
`It 'can filter on object propertes'`
}

**Comment by vexx32** [comment]
🤔 not sure how/why you'd be getting those exceptions? `Get-ChildItem -Recurse -Depth 2` doesn't emit exceptions for me, even if there aren't two levels for it to go into?

**Comment by DEberhardt** [comment]
`$Home` is targeting my user folder, maybe it is a local issue... 
I went and removed this directory... must be an old relic from somewhere. 
The error is now gone. I also tested with `$PSHOME` which did work as well...

Close?

**Comment by vexx32** [comment]
Aye, I'll close it for now. Eventually we need to sort out #183 and this should go away as a possible issue then as well. 🙂
