### ISSUE TITLE
measure-karma status ends with run 'rake -Meditate'

### ISSUE THREAD

**Issue by Tuxhedoh** [vexx32/PSKoans#90]
I'm sure this is an oversight. I'd be happy  to fix, though not sure how I can.

**Comment by vexx32** [comment]
Ah, yup, it had this listed as an alias for a while, but I removed it because it was conflicting with the actual build tool `rake` for Ruby projects.

No worries, just some text edits. 😄  I'll get it done in the near future.

**Comment by vexx32** [comment]
I've already fixed this, actually. It'll be in the next release!
