### ISSUE TITLE
Modulus Errors

### ISSUE THREAD

**Issue by Tuxhedoh** [vexx32/PSKoans#92]
https://github.com/vexx32/PSKoans/blob/87d30dacd7b2a9df71339e44b124ddc4236e44af/PSKoans/Koans/Foundations/AboutAssignmentAndArithmetic.Koans.ps1#L136 

I understand what you're going for here, but I'm not convinced that this is a good excersize. I hate pointing out something without offering a fix.

**Comment by vexx32** [comment]
Does running the `Measure-Karma` command when at this test point not show the expected error message?

**Comment by Tuxhedoh** [comment]
I'm guessing it does, though didn't think that was a valid way of finding the answer.

**Comment by vexx32** [comment]
In this case, I think it is. 😄 

It's more intended to simply illustrate that a) an error will be thrown, and b) what that error looks like, so folks can learn a little of what to look for when their code breaks in certain ways. 😁

**Comment by Tuxhedoh** [comment]
Of course if they just run the code, they don't even see that error message by default. 
![image](https://user-images.githubusercontent.com/24434458/48626219-515d7d80-e97f-11e8-8b67-21ac0f33228a.png)

I answered this with `System.Management.Automation.RuntimeException`, because that's the actual exceptiontype (I think).  Where it looks like you're expecting the Exception.Message. I don't know. Just offering feedback.

**Comment by vexx32** [comment]
I believe this has been addressed in the recent release(s). 😄
