### ISSUE TITLE
It seems the quotation marks are borking this.

### ISSUE THREAD

**Issue by Tuxhedoh** [vexx32/PSKoans#95]
https://github.com/vexx32/PSKoans/blob/3563a02ddd54f77188ae7e463bcfc017a83280c8/PSKoans/Koans/Foundations/AboutStrings.Koans.ps1#L35

![image](https://user-images.githubusercontent.com/24434458/48631677-12362900-e98d-11e8-8e3d-d3d0bc393bbc.png)

From the about_quotationRules

>  To make double-quotation marks appear in a string, enclose the entire
    string in single quotation marks. For example:

        'As they say, "live and learn."'

    The output of this command is:

        As they say, "live and learn."

    You can also enclose a single-quoted string in a double-quoted string.
    For example:

        "As they say, 'live and learn.'"

    The output of this command is:

        As they say, 'live and learn.'

    Or, double the quotation marks around a double-quoted phrase. For
    example:

        "As they say, ""live and learn."""

    The output of this command is:

        As they say, "live and learn."

    To include a single quotation mark in a single-quoted string, use a
    second consecutive single quote. For example:

        'don''t'

    The output of this command is:

        don't``

**Comment by vexx32** [comment]
Is this actually breaking? This is meant to illustrate different methods of including quotation marks in a string; doubling up the quotation marks to insert them into a string is a valid way of doing so. 😄
